'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import MonthPicker from '@/component/MonthPicker';
import { businessMonthFromInstant, formatBusinessMonthInput } from '@/lib/business-date';
import type { PayrollMonthDTO } from '@/services/server/payroll';

const money = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND' });
export default function AdminPayrollPage() {
  const [month, setMonth] = useState(() => formatBusinessMonthInput(businessMonthFromInstant(new Date())));
  const [rows, setRows] = useState<PayrollMonthDTO[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [canSettle, setCanSettle] = useState(false); const [canAdjust, setCanAdjust] = useState(false); const [activeAction, setActiveAction] = useState<string | null>(null); const lock = useRef(false); const requestSequence = useRef(0);
  const load = useCallback(async () => { const sequence = ++requestSequence.current; setLoading(true); setError(''); try { const response = await fetch(`/api/admin/payroll?month=${month}`, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.message); if (sequence !== requestSequence.current) return; setRows(body.payroll); setCanSettle(body.canSettle); setCanAdjust(body.canAdjust); } catch (e) { if (sequence === requestSequence.current) setError(e instanceof Error ? e.message : 'Không thể tải dữ liệu lương.'); } finally { if (sequence === requestSequence.current) setLoading(false); } }, [month]);
  useEffect(() => { void load(); return () => { requestSequence.current += 1; }; }, [load]);
  async function settle(employeeId: string) { if (lock.current || !confirm('Xác nhận quyết toán? Bản gốc sẽ không thể sửa hoặc ghi đè.')) return; lock.current = true; setActiveAction(`settle:${employeeId}`); try { const response = await fetch('/api/admin/payroll', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'settle', employeeId, month }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Không thể quyết toán.'); } finally { lock.current = false; setActiveAction(null); } }
  async function adjust(settlementId: string) { if (lock.current) return; const amount = prompt('Nhập số tiền điều chỉnh (âm để khấu trừ):'); if (!amount) return; const reason = prompt('Nhập lý do điều chỉnh (bắt buộc):'); if (!reason) return; lock.current = true; setActiveAction(`adjust:${settlementId}`); try { const response = await fetch('/api/admin/payroll', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'adjust', settlementId, amount, reason }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo điều chỉnh.'); } finally { lock.current = false; setActiveAction(null); } }
  return <section className="space-y-5 p-5 sm:p-8"><div><h1 className="text-xl font-bold">Quyết toán lương tháng</h1><p className="mt-1 text-sm text-slate-400">Bản quyết toán là ảnh chụp bất biến. Mọi sửa đổi được ghi thành điều chỉnh riêng.</p></div><div className="max-w-xs"><MonthPicker value={month} onChange={setMonth} /></div>{error && <div role="alert" className="rounded-lg border border-red-500/30 bg-red-950/30 p-3 text-sm text-red-200">{error} <button onClick={() => void load()} disabled={loading} className="ml-2 underline disabled:opacity-60">{loading ? 'Đang thử lại...' : 'Thử lại'}</button></div>}{loading ? <p className="text-sm text-slate-400">Đang tải bảng lương...</p> : <div className="overflow-x-auto rounded-xl border border-slate-800"><table className="w-full text-left text-sm"><thead className="bg-slate-900 text-slate-400"><tr><th className="p-3">Nhân viên</th><th>Giờ / ca</th><th>Lương tính</th><th>Điều chỉnh</th><th>Thực nhận</th><th>Trạng thái</th><th /></tr></thead><tbody>{rows.map(row => <tr key={row.employeeId} className="border-t border-slate-800"><td className="p-3 font-medium">{row.employeeName}</td><td>{row.workedHours} giờ / {row.calculatedShifts} ca</td><td>{money.format(row.baseSalary)}</td><td>{money.format(row.adjustmentTotal)}</td><td className="font-bold">{money.format(row.finalPayableAmount)}</td><td>{row.settlementStatus === 'SETTLED' ? 'Đã quyết toán' : 'Chưa quyết toán'}</td><td className="p-3">{row.settlementStatus === 'UNSETTLED' && canSettle && <button disabled={activeAction !== null} onClick={() => void settle(row.employeeId)} className="rounded-lg bg-blue-600 px-3 py-2 font-bold hover:bg-blue-500 disabled:opacity-60">{activeAction === `settle:${row.employeeId}` ? 'Đang xác nhận...' : 'Xác nhận'}</button>}{row.settlementStatus === 'SETTLED' && row.settlementId && canAdjust && <button disabled={activeAction !== null} onClick={() => void adjust(row.settlementId!)} className="rounded-lg border border-slate-600 px-3 py-2 font-bold hover:bg-slate-800 disabled:opacity-60">{activeAction === `adjust:${row.settlementId}` ? 'Đang điều chỉnh...' : 'Điều chỉnh'}</button>}</td></tr>)}</tbody></table>{rows.length === 0 && <p className="p-8 text-center text-slate-400">Không có dữ liệu lương trong tháng đã chọn.</p>}</div>}</section>;
}
