-- DRAFT ONLY - DO NOT RUN WITHOUT LIVE APPROVAL.
-- Scope: Task Assignment Foundation (Phase 2) for normalized child tasks,
-- stable assignee employee IDs, deadlines, comments, activity, and notification outbox.
-- Required before execution: live schema audit, approval, maintenance window,
-- rollback acceptance, and backfill conflict review.
-- Preconditions expected from prior approved foundations:
--   public.projects, public.phases, public.tasks, public.employees, public.project_members
--   public.current_employee_id()
--   public.can_view_project(bigint)

begin;

do $$
begin
  if to_regclass('public.projects') is null then
    raise exception 'Precondition failed: public.projects does not exist.';
  end if;
  if to_regclass('public.phases') is null then
    raise exception 'Precondition failed: public.phases does not exist.';
  end if;
  if to_regclass('public.tasks') is null then
    raise exception 'Precondition failed: public.tasks does not exist.';
  end if;
  if to_regclass('public.employees') is null then
    raise exception 'Precondition failed: public.employees does not exist.';
  end if;
  if to_regclass('public.project_members') is null then
    raise exception 'Precondition failed: public.project_members does not exist.';
  end if;
  if to_regprocedure('public.current_employee_id()') is null then
    raise exception 'Precondition failed: public.current_employee_id() does not exist.';
  end if;
  if to_regprocedure('public.can_view_project(bigint)') is null then
    raise exception 'Precondition failed: public.can_view_project(bigint) does not exist.';
  end if;
end $$;


alter table public.tasks
  add column if not exists project_id bigint references public.projects(id) on delete cascade,
  add column if not exists phase_id bigint references public.phases(id) on delete set null,
  add column if not exists parent_task_id bigint references public.tasks(id) on delete set null,
  add column if not exists title text,
  add column if not exists description text,
  add column if not exists assignee_employee_id bigint references public.employees(id) on delete set null,
  add column if not exists deadline timestamptz,
  add column if not exists status text,
  add column if not exists created_by_employee_id bigint references public.employees(id) on delete set null,
  add column if not exists updated_by_employee_id bigint references public.employees(id) on delete set null,
  add column if not exists assigned_by_employee_id bigint references public.employees(id) on delete set null,
  add column if not exists assigned_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz;

alter table public.tasks
  add constraint tasks_assignment_status_check
  check (status is null or status in (
    'BACKLOG',
    'READY',
    'IN_PROGRESS',
    'PENDING_REVIEW',
    'REVISION_REQUIRED',
    'APPROVED',
    'BLOCKED',
    'ON_HOLD',
    'COMPLETED',
    'CANCELLED'
  )) not valid;

alter table public.tasks
  add constraint tasks_assignment_title_not_blank
  check (title is null or length(btrim(title)) > 0) not valid;

create index if not exists tasks_project_id_idx
  on public.tasks(project_id)
  where project_id is not null;

create index if not exists tasks_project_phase_idx
  on public.tasks(project_id, phase_id)
  where project_id is not null;

create index if not exists tasks_parent_task_id_idx
  on public.tasks(parent_task_id)
  where parent_task_id is not null;

create index if not exists tasks_assignee_employee_id_idx
  on public.tasks(assignee_employee_id)
  where assignee_employee_id is not null;

create index if not exists tasks_deadline_idx
  on public.tasks(deadline)
  where deadline is not null;

create table if not exists public.task_comments (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  employee_id bigint references public.employees(id) on delete set null,
  body text not null check (length(btrim(body)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists task_comments_task_created_idx
  on public.task_comments(task_id, created_at desc);

create index if not exists task_comments_project_created_idx
  on public.task_comments(project_id, created_at desc);

create table if not exists public.project_activity (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  task_id bigint references public.tasks(id) on delete set null,
  actor_employee_id bigint references public.employees(id) on delete set null,
  activity_type text not null check (activity_type in (
    'TASK_CREATED',
    'TASK_UPDATED',
    'TASK_ASSIGNED',
    'STATUS_CHANGED',
    'COMMENT_ADDED'
  )),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists project_activity_project_created_idx
  on public.project_activity(project_id, created_at desc);

create index if not exists project_activity_task_created_idx
  on public.project_activity(task_id, created_at desc)
  where task_id is not null;

create table if not exists public.task_notifications (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  task_id bigint not null references public.tasks(id) on delete cascade,
  recipient_employee_id bigint not null references public.employees(id) on delete cascade,
  notification_type text not null check (notification_type in (
    'TASK_ASSIGNED',
    'TASK_STATUS_CHANGED',
    'TASK_COMMENT_ADDED',
    'TASK_DEADLINE_CHANGED'
  )),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'PENDING' check (status in ('PENDING', 'SENT', 'FAILED', 'CANCELLED')),
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists task_notifications_recipient_status_idx
  on public.task_notifications(recipient_employee_id, status, created_at desc);

-- RLS preparation. Policies intentionally use existing project membership helpers.
alter table public.task_comments enable row level security;
alter table public.project_activity enable row level security;
alter table public.task_notifications enable row level security;

create policy "task comments project access select"
  on public.task_comments
  for select
  to authenticated
  using (public.can_view_project(project_id));

create policy "project activity project access select"
  on public.project_activity
  for select
  to authenticated
  using (public.can_view_project(project_id));

create policy "task notifications recipient select"
  on public.task_notifications
  for select
  to authenticated
  using (recipient_employee_id = public.current_employee_id());

-- No browser INSERT/UPDATE/DELETE policies are added in this draft.
-- Mutations remain server-mediated after requireProjectMembershipAction(TASK_MANAGE).

commit;
