-- DRAFT FOR OPERATOR REVIEW. Not registered under supabase/migrations and not executed.
begin;
alter table public.employees
 add column if not exists birth_date date,
 add column if not exists gender text,
 add column if not exists address text,
 add column if not exists avatar_url text,
 add column if not exists personal_notes text,
 add column if not exists employment_type text,
 add column if not exists employment_start_date date,
 add column if not exists manager_employee_id bigint references public.employees(id) on delete set null;
create index if not exists employees_manager_employee_id_idx on public.employees(manager_employee_id);

create table if not exists public.employee_audit_events (
 id bigint generated by default as identity primary key,
 employee_id bigint not null references public.employees(id) on delete restrict,
 field_name text not null,
 previous_value text,
 new_value text,
 actor_employee_id bigint references public.employees(id) on delete set null,
 occurred_at timestamptz not null default clock_timestamp(),
 reason text
);
alter table public.employee_audit_events enable row level security;
revoke all on table public.employee_audit_events from anon;
grant select on table public.employee_audit_events to authenticated;
create policy "employee audit admin view" on public.employee_audit_events for select to authenticated
 using (public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('EMPLOYEE_VIEW'));

create or replace function public.capture_employee_safe_audit() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare field text; before_value text; after_value text;
begin
 foreach field in array array['full_name','email','phone','title','branch_code','status','role','birth_date','gender','address','avatar_url','personal_notes','employment_type','employment_start_date','manager_employee_id'] loop
   before_value := to_jsonb(old)->>field; after_value := to_jsonb(new)->>field;
   if before_value is distinct from after_value then
     insert into public.employee_audit_events(employee_id,field_name,previous_value,new_value,actor_employee_id)
     values(new.id,field,before_value,after_value,public.current_employee_id());
   end if;
 end loop;
 return new;
end $$;
revoke all on function public.capture_employee_safe_audit() from public, anon, authenticated;
drop trigger if exists employees_capture_safe_audit on public.employees;
create trigger employees_capture_safe_audit after update on public.employees for each row execute function public.capture_employee_safe_audit();
commit;
