-- DRAFT ONLY - DO NOT RUN WITHOUT EXPLICIT APPROVAL.
-- Phase status/dependency mutation foundation forward draft.

begin;

-- Precondition checks intentionally fail fast before schema mutation.
do $$
begin
  if to_regclass('public.projects') is null then
    raise exception 'Precondition failed: public.projects does not exist.';
  end if;
  if to_regclass('public.phases') is null then
    raise exception 'Precondition failed: public.phases does not exist.';
  end if;
  if to_regclass('public.employees') is null then
    raise exception 'Precondition failed: public.employees does not exist.';
  end if;
  if to_regprocedure('public.can_view_project(bigint)') is null then
    raise exception 'Precondition failed: public.can_view_project(bigint) does not exist.';
  end if;
end $$;

alter table public.phases
  add column if not exists status text,
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz,
  add column if not exists updated_by_employee_id bigint;

update public.phases
set status = case
  when completed_at is not null then 'COMPLETED'
  when order_index = 0 then 'ACTIVE'
  else 'LOCKED'
end
where status is null;

alter table public.phases
  alter column status set default 'LOCKED',
  alter column status set not null,
  alter column updated_at set default now();

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'phases_status_check'
      and conrelid = 'public.phases'::regclass
  ) then
    alter table public.phases
      add constraint phases_status_check
      check (status in ('ACTIVE', 'LOCKED', 'COMPLETED', 'BLOCKED', 'REVIEW', 'CANCELLED'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'phases_updated_by_employee_id_fkey'
      and conrelid = 'public.phases'::regclass
  ) then
    alter table public.phases
      add constraint phases_updated_by_employee_id_fkey
      foreign key (updated_by_employee_id)
      references public.employees(id)
      on update cascade
      on delete set null;
  end if;
end $$;

create table if not exists public.phase_status_history (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on update cascade on delete cascade,
  phase_id bigint not null references public.phases(id) on update cascade on delete cascade,
  actor_employee_id bigint not null references public.employees(id) on update cascade on delete restrict,
  action text not null,
  old_status text,
  new_status text not null,
  reason text not null,
  note text,
  override_flag boolean not null default false,
  created_at timestamptz not null default now(),
  constraint phase_status_history_action_check check (action in ('COMPLETE', 'LOCK', 'UNLOCK', 'REOPEN', 'SKIP', 'CANCEL', 'OVERRIDE_LOCK')),
  constraint phase_status_history_new_status_check check (new_status in ('ACTIVE', 'LOCKED', 'COMPLETED', 'BLOCKED', 'REVIEW', 'CANCELLED')),
  constraint phase_status_history_reason_check check (length(btrim(reason)) > 0)
);

create index if not exists phases_project_order_idx on public.phases(project_id, order_index);
create index if not exists phases_project_status_idx on public.phases(project_id, status);
create index if not exists phase_status_history_project_phase_created_idx on public.phase_status_history(project_id, phase_id, created_at desc);

alter table public.phase_status_history enable row level security;

drop policy if exists "phase status history project view select" on public.phase_status_history;
create policy "phase status history project view select"
  on public.phase_status_history
  for select
  to authenticated
  using (public.can_view_project(project_id));

commit;
