-- Draft-only forward package. Requires explicit LIVE_APPROVAL_REQUIRED before execution.
begin;

do $$
begin
  if to_regclass('public.attendance') is null
     or to_regclass('public.employees') is null
     or to_regclass('public.attendance_cancellation_audit') is null
     or to_regprocedure('public.current_employee_id()') is null
     or to_regprocedure('public.has_workspace_access(text)') is null
     or to_regprocedure('public.has_permission(text)') is null then
    raise exception 'Attendance multi-check precondition failed';
  end if;

  if not exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'attendance'
      and column_name = 'cancelled_at'
  ) then
    raise exception 'Attendance multi-check precondition failed: cancellation columns are unavailable';
  end if;

  if exists (
    select 1 from public.attendance
    where cancelled_at is null
    group by employee_id, work_date, shift_name
    having count(*) > 1
  ) then
    raise exception 'Attendance multi-check precondition failed: duplicate active aggregate rows exist';
  end if;
end $$;

create unique index if not exists attendance_employee_date_shift_active_idx
  on public.attendance(employee_id, work_date, shift_name)
  where cancelled_at is null;

create table if not exists public.attendance_operation_audit (
  id bigint generated by default as identity primary key,
  attendance_id bigint null references public.attendance(id) on delete restrict,
  employee_id bigint not null references public.employees(id) on delete restrict,
  actor_employee_id bigint not null references public.employees(id) on delete restrict,
  operation text not null check (operation in ('CREATE', 'UPDATE', 'DELETE')),
  reason text not null check (length(btrim(reason)) >= 10),
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  correlation_id uuid not null,
  occurred_at timestamptz not null default now()
);

alter table public.attendance_operation_audit enable row level security;
revoke all on public.attendance_operation_audit from public, anon, authenticated;
grant select on public.attendance_operation_audit to authenticated;
drop policy if exists "attendance operation audit admin select" on public.attendance_operation_audit;
create policy "attendance operation audit admin select"
on public.attendance_operation_audit for select to authenticated
using (
  public.has_workspace_access('ADMIN_WORKSPACE')
  and public.has_permission('ATTENDANCE_VIEW')
);

create or replace function public.attendance_audit_state(row_value public.attendance)
returns jsonb language sql immutable as $$
  select jsonb_build_object(
    'attendance_id', row_value.id,
    'employee_id', row_value.employee_id,
    'work_date', row_value.work_date,
    'shift_name', row_value.shift_name,
    'check_in', row_value.check_in,
    'check_out', row_value.check_out,
    'total_hours', row_value.total_hours,
    'total_salary', row_value.total_salary,
    'status', row_value.status,
    'cancelled_at', row_value.cancelled_at
  );
$$;

create or replace function public.staff_attendance_multi_mutation(
  p_action text,
  p_work_date date,
  p_shift_name text,
  p_check_time time without time zone
)
returns setof public.attendance
language plpgsql
security invoker
set search_path = public, auth, pg_temp
as $$
declare
  actor bigint := public.current_employee_id();
  row_value public.attendance%rowtype;
  hourly_rate numeric := 0;
  worked_minutes integer;
  worked_hours numeric;
begin
  if actor is null or not public.has_workspace_access('STAFF_WORKSPACE') then
    raise exception 'Staff attendance access denied' using errcode = '42501';
  end if;
  if p_action not in ('check_in', 'check_out') or p_work_date is null or btrim(coalesce(p_shift_name, '')) = '' or p_check_time is null then
    raise exception 'Invalid staff attendance mutation' using errcode = '22023';
  end if;

  select * into row_value
  from public.attendance
  where employee_id = actor and work_date = p_work_date and shift_name = p_shift_name and cancelled_at is null
  for update;

  if p_action = 'check_in' then
    if not found then
      insert into public.attendance(employee_id, work_date, shift_name, check_in, check_out, total_hours, total_salary, status)
      values (actor, p_work_date, p_shift_name, p_check_time, null, null, null, 'PRESENT')
      returning * into row_value;
    elsif row_value.check_out is null then
      raise exception 'Attendance shift is already open' using errcode = '23505';
    else
      update public.attendance
      set check_out = null, total_hours = null, total_salary = null, status = 'PRESENT'
      where id = row_value.id
      returning * into row_value;
    end if;
  else
    if not found or row_value.check_in is null or row_value.check_out is not null then
      raise exception 'Attendance shift is not open' using errcode = '55000';
    end if;
    if p_check_time < row_value.check_in then
      raise exception 'Attendance check-out precedes check-in' using errcode = '22007';
    end if;
    worked_minutes := greatest(0, floor(extract(epoch from (p_check_time - row_value.check_in)) / 60)::integer);
    worked_hours := round(worked_minutes::numeric / 60, 2);
    select coalesce(e.hourly_rate, 0) into hourly_rate from public.employees e where e.id = actor;
    update public.attendance
    set check_out = p_check_time,
        total_hours = worked_hours,
        total_salary = case when worked_hours <= 0 or hourly_rate <= 0 then 0 else round(worked_hours * hourly_rate) end,
        status = 'PRESENT'
    where id = row_value.id
    returning * into row_value;
  end if;

  return next row_value;
end;
$$;

revoke all on function public.staff_attendance_multi_mutation(text,date,text,time without time zone) from public, anon;
grant execute on function public.staff_attendance_multi_mutation(text,date,text,time without time zone) to authenticated;

create or replace function public.admin_attendance_mutation(
  p_operation text,
  p_attendance_id bigint,
  p_employee_id bigint,
  p_work_date date,
  p_shift_name text,
  p_check_in time without time zone,
  p_check_out time without time zone,
  p_reason text,
  p_correlation_id uuid
)
returns setof public.attendance
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  actor bigint := public.current_employee_id();
  before_row public.attendance%rowtype;
  after_row public.attendance%rowtype;
  hourly_rate numeric := 0;
  worked_minutes integer;
  worked_hours numeric;
begin
  if actor is null or not public.has_workspace_access('ADMIN_WORKSPACE') or not public.has_permission('ATTENDANCE_MANAGE') then
    raise exception 'Admin attendance access denied' using errcode = '42501';
  end if;
  if p_operation not in ('CREATE', 'UPDATE', 'DELETE') or length(btrim(coalesce(p_reason, ''))) < 10 or p_correlation_id is null then
    raise exception 'Invalid audited attendance mutation' using errcode = '22023';
  end if;

  if p_operation = 'CREATE' then
    if p_employee_id is null or p_work_date is null or btrim(coalesce(p_shift_name, '')) = '' or p_check_in is null or p_check_out is null or p_check_out < p_check_in then
      raise exception 'Invalid attendance interval' using errcode = '22007';
    end if;
    worked_minutes := greatest(0, floor(extract(epoch from (p_check_out - p_check_in)) / 60)::integer);
    worked_hours := round(worked_minutes::numeric / 60, 2);
    select coalesce(e.hourly_rate, 0) into hourly_rate from public.employees e where e.id = p_employee_id;
    insert into public.attendance(employee_id, work_date, shift_name, check_in, check_out, total_hours, total_salary, status)
    values (p_employee_id, p_work_date, p_shift_name, p_check_in, p_check_out, worked_hours,
      case when worked_hours <= 0 or hourly_rate <= 0 then 0 else round(worked_hours * hourly_rate) end, 'PRESENT')
    returning * into after_row;
    insert into public.attendance_operation_audit(attendance_id, employee_id, actor_employee_id, operation, reason, before_state, after_state, correlation_id)
    values (after_row.id, after_row.employee_id, actor, 'CREATE', p_reason, '{}'::jsonb, public.attendance_audit_state(after_row), p_correlation_id);
  elsif p_operation = 'UPDATE' then
    select * into before_row from public.attendance where id = p_attendance_id for update;
    if not found or before_row.cancelled_at is not null or p_employee_id is null or p_check_in is null or p_check_out is null or p_check_out < p_check_in then
      raise exception 'Attendance row cannot be updated' using errcode = '55000';
    end if;
    if p_employee_id is distinct from before_row.employee_id then
      raise exception 'Attendance employee cannot be changed' using errcode = '22023';
    end if;
    if to_regclass('public.payroll_settlements') is not null and exists (
      select 1 from public.payroll_settlements s
      cross join lateral jsonb_array_elements(s.attendance_summary) item
      where item ->> 'attendance_id' = before_row.id::text
    ) then
      raise exception 'Attendance row is referenced by finalized payroll' using errcode = '55000';
    end if;
    worked_minutes := greatest(0, floor(extract(epoch from (p_check_out - p_check_in)) / 60)::integer);
    worked_hours := round(worked_minutes::numeric / 60, 2);
    select coalesce(e.hourly_rate, 0) into hourly_rate from public.employees e where e.id = before_row.employee_id;
    update public.attendance
    set work_date = coalesce(p_work_date, before_row.work_date),
        shift_name = coalesce(nullif(btrim(p_shift_name), ''), before_row.shift_name),
        check_in = p_check_in,
        check_out = p_check_out,
        total_hours = worked_hours,
        total_salary = case when worked_hours <= 0 or hourly_rate <= 0 then 0 else round(worked_hours * hourly_rate) end,
        status = 'PRESENT'
    where id = before_row.id
    returning * into after_row;
    insert into public.attendance_operation_audit(attendance_id, employee_id, actor_employee_id, operation, reason, before_state, after_state, correlation_id)
    values (after_row.id, after_row.employee_id, actor, 'UPDATE', p_reason, public.attendance_audit_state(before_row), public.attendance_audit_state(after_row), p_correlation_id);
  else
    select * into before_row from public.attendance where id = p_attendance_id for update;
    if not found or before_row.cancelled_at is not null then
      raise exception 'Attendance row cannot be deleted' using errcode = '55000';
    end if;
    if to_regclass('public.payroll_settlements') is not null and exists (
      select 1 from public.payroll_settlements s
      cross join lateral jsonb_array_elements(s.attendance_summary) item
      where item ->> 'attendance_id' = before_row.id::text
    ) then
      raise exception 'Attendance row is referenced by finalized payroll' using errcode = '55000';
    end if;
    update public.attendance
    set check_out = null, total_hours = null, total_salary = null, status = 'CANCELLED',
        cancellation_reason = p_reason, cancelled_by_employee_id = actor, cancelled_at = now()
    where id = before_row.id
    returning * into after_row;
    insert into public.attendance_cancellation_audit(
      attendance_id, employee_id, event_type, previous_status, resulting_status,
      reason, actor_employee_id, occurred_at, details
    )
    values (
      after_row.id, after_row.employee_id, 'CANCELLED', before_row.status,
      after_row.status, p_reason, actor, now(),
      jsonb_build_object('correlation_id', p_correlation_id, 'operation', 'DELETE')
    );
    insert into public.attendance_operation_audit(attendance_id, employee_id, actor_employee_id, operation, reason, before_state, after_state, correlation_id)
    values (after_row.id, after_row.employee_id, actor, 'DELETE', p_reason, public.attendance_audit_state(before_row), public.attendance_audit_state(after_row), p_correlation_id);
  end if;

  return next after_row;
end;
$$;

revoke all on function public.admin_attendance_mutation(text,bigint,bigint,date,text,time without time zone,time without time zone,text,uuid) from public, anon, authenticated;
grant execute on function public.admin_attendance_mutation(text,bigint,bigint,date,text,time without time zone,time without time zone,text,uuid) to authenticated;

commit;
