-- SUPERSEDED — DO NOT EXECUTE.
--
-- This draft assumed authenticated callers had the required financial_ledger
-- mutation RLS policies. Production preflight on 2026-08-09 showed that the
-- authenticated role has only the Admin SELECT policy, so this plan is no
-- longer valid and must not be promoted or replayed.
--
-- The delivered replacement is tracked at:
--   supabase/migrations/20260809004500_finance_linked_ledger_atomic_edit.sql
-- Live Supabase migration history records it as:
--   20260808175603 finance_linked_ledger_atomic_edit
--
-- The replacement RPC remains SECURITY INVOKER but EXECUTE is revoked from
-- public/anon/authenticated and granted only to service_role. Application
-- authorization stays server-side behind ADMIN_WORKSPACE + FINANCE_UPDATE.
