-- Phase Template release-one forward package (REVIEW ONLY).
-- Do not move to supabase/migrations or execute without protected approval.
-- Empty catalog by design: this package inserts no template business rows.

begin;

select pg_advisory_xact_lock(hashtextextended('luminal:phase-template:v1', 0));

insert into public.permissions (code, description)
values ('PHASE_TEMPLATE_MANAGE', 'Manage project phase templates and version history')
on conflict (code) do update set description = excluded.description;

alter table public.projects add column start_date date null;
alter table public.projects
  add constraint projects_start_date_before_deadline_check
  check (start_date is null or project_deadline is null or start_date <= project_deadline);
comment on column public.projects.start_date is
  'Canonical project calendar anchor; required only when a Phase Template is applied.';

alter table public.tasks add column is_required boolean null;
alter table public.tasks add column requires_review boolean null;
comment on column public.tasks.is_required is
  'Template-derived task requirement; NULL preserves legacy/unspecified semantics.';
comment on column public.tasks.requires_review is
  'Template-derived review requirement; NULL preserves legacy/unspecified semantics.';

create table public.phase_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text generated always as (lower(btrim(name))) stored,
  description text null,
  project_type text not null default 'GENERAL',
  status text not null default 'ACTIVE',
  current_version_id bigint null,
  created_by_employee_id bigint not null references public.employees(id) on delete restrict,
  updated_by_employee_id bigint not null references public.employees(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint phase_templates_name_not_blank check (length(btrim(name)) > 0),
  constraint phase_templates_project_type_check check (project_type = 'GENERAL'),
  constraint phase_templates_status_check check (status in ('ACTIVE', 'ARCHIVED')),
  constraint phase_templates_normalized_name_unique unique (project_type, normalized_name)
);

create table public.phase_template_versions (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.phase_templates(id) on delete restrict,
  version_number integer not null,
  status text not null default 'DRAFT',
  source_version_id bigint null references public.phase_template_versions(id) on delete restrict,
  published_at timestamptz null,
  archived_at timestamptz null,
  created_by_employee_id bigint not null references public.employees(id) on delete restrict,
  updated_by_employee_id bigint not null references public.employees(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint phase_template_versions_number_positive check (version_number > 0),
  constraint phase_template_versions_status_check check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  constraint phase_template_versions_lifecycle_check check (
    (status = 'DRAFT' and published_at is null and archived_at is null)
    or (status = 'PUBLISHED' and published_at is not null and archived_at is null)
    or (status = 'ARCHIVED' and archived_at is not null)
  ),
  constraint phase_template_versions_template_number_unique unique (template_id, version_number)
);

alter table public.phase_templates
  add constraint phase_templates_current_version_id_fkey
  foreign key (current_version_id) references public.phase_template_versions(id) on delete restrict;

create unique index phase_template_versions_one_draft_idx
  on public.phase_template_versions(template_id) where status = 'DRAFT';
create unique index phase_template_versions_one_published_idx
  on public.phase_template_versions(template_id) where status = 'PUBLISHED';
create index phase_template_versions_source_version_idx
  on public.phase_template_versions(source_version_id) where source_version_id is not null;

create table public.phase_template_stages (
  id bigint generated by default as identity primary key,
  version_id bigint not null references public.phase_template_versions(id) on delete restrict,
  name text not null,
  normalized_name text generated always as (lower(btrim(name))) stored,
  order_index integer not null,
  start_offset_days integer null,
  duration_days integer null,
  requires_review boolean not null default false,
  created_at timestamptz not null default now(),
  constraint phase_template_stages_name_not_blank check (length(btrim(name)) > 0),
  constraint phase_template_stages_order_positive check (order_index > 0),
  constraint phase_template_stages_offsets_nonnegative check (start_offset_days >= 0 and duration_days >= 0),
  constraint phase_template_stages_version_order_unique unique (version_id, order_index),
  constraint phase_template_stages_version_name_unique unique (version_id, normalized_name)
);

create table public.phase_template_tasks (
  id bigint generated by default as identity primary key,
  stage_id bigint not null references public.phase_template_stages(id) on delete restrict,
  name text not null,
  normalized_name text generated always as (lower(btrim(name))) stored,
  description text null,
  order_index integer not null,
  start_offset_days integer null,
  is_required boolean not null default true,
  requires_review boolean not null default false,
  assignee_role_code text null,
  created_at timestamptz not null default now(),
  constraint phase_template_tasks_name_not_blank check (length(btrim(name)) > 0),
  constraint phase_template_tasks_order_positive check (order_index > 0),
  constraint phase_template_tasks_offset_nonnegative check (start_offset_days >= 0),
  constraint phase_template_tasks_role_check check (
    assignee_role_code is null or assignee_role_code in (
      'PROJECT_OWNER', 'PROJECT_MANAGER', 'CREATIVE_LEAD', 'CONTRIBUTOR'
    )
  ),
  constraint phase_template_tasks_stage_order_unique unique (stage_id, order_index),
  constraint phase_template_tasks_stage_name_unique unique (stage_id, normalized_name)
);

create table public.phase_template_applications (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete restrict,
  template_id bigint not null references public.phase_templates(id) on delete restrict,
  version_id bigint not null references public.phase_template_versions(id) on delete restrict,
  applied_by_employee_id bigint not null references public.employees(id) on delete restrict,
  applied_at timestamptz not null default now(),
  clone_summary jsonb not null default '{}'::jsonb,
  constraint phase_template_applications_project_unique unique (project_id),
  constraint phase_template_applications_summary_object check (jsonb_typeof(clone_summary) = 'object')
);

create table public.phase_template_audit (
  id bigint generated by default as identity primary key,
  template_id bigint null references public.phase_templates(id) on delete set null,
  version_id bigint null references public.phase_template_versions(id) on delete set null,
  actor_employee_id bigint not null references public.employees(id) on delete restrict,
  action text not null,
  reason text null,
  before_data jsonb null,
  after_data jsonb null,
  occurred_at timestamptz not null default now(),
  retain_until date generated always as ((occurred_at at time zone 'UTC')::date + 2557) stored,
  constraint phase_template_audit_action_check check (action in (
    'DRAFT_CREATED', 'DRAFT_UPDATED', 'VERSION_CLONED', 'PUBLISHED',
    'ARCHIVED', 'RESTORED', 'DRAFT_DELETED', 'APPLIED'
  )),
  constraint phase_template_audit_reason_check check (
    action not in ('PUBLISHED', 'ARCHIVED', 'RESTORED', 'DRAFT_DELETED')
    or coalesce(length(btrim(reason)), 0) > 0
  ),
  constraint phase_template_audit_before_object check (before_data is null or jsonb_typeof(before_data) = 'object'),
  constraint phase_template_audit_after_object check (after_data is null or jsonb_typeof(after_data) = 'object')
);

create index phase_template_stages_version_idx on public.phase_template_stages(version_id);
create index phase_template_tasks_stage_idx on public.phase_template_tasks(stage_id);
create index phase_template_applications_template_idx on public.phase_template_applications(template_id);
create index phase_template_applications_version_idx on public.phase_template_applications(version_id);
create index phase_template_applications_actor_idx on public.phase_template_applications(applied_by_employee_id);
create index phase_template_audit_template_time_idx on public.phase_template_audit(template_id, occurred_at desc);
create index phase_template_audit_version_idx on public.phase_template_audit(version_id) where version_id is not null;
create index phase_template_audit_actor_idx on public.phase_template_audit(actor_employee_id);
create index phase_template_audit_retention_idx on public.phase_template_audit(retain_until);

create function public.phase_template_reject_immutable_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'phase_template_immutable_row' using errcode = 'P0001';
end;
$$;

create function public.phase_template_protect_audit_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE'
    and old.version_id is not null and new.version_id is null
    and new.id = old.id
    and new.template_id is not distinct from old.template_id
    and new.actor_employee_id = old.actor_employee_id
    and new.action = old.action
    and new.reason is not distinct from old.reason
    and new.before_data is not distinct from old.before_data
    and new.after_data is not distinct from old.after_data
    and new.occurred_at = old.occurred_at
    and new.retain_until = old.retain_until then
    return new;
  end if;
  raise exception 'phase_template_audit_immutable_row' using errcode = 'P0001';
end;
$$;

create function public.phase_template_validate_current_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.current_version_id is not null and not exists (
    select 1
    from public.phase_template_versions version
    where version.id = new.current_version_id
      and version.template_id = new.id
      and version.status = 'PUBLISHED'
  ) then
    raise exception 'phase_template_current_version_invalid' using errcode = '23514';
  end if;
  return new;
end;
$$;

create trigger phase_templates_current_version_guard
before insert or update of current_version_id on public.phase_templates
for each row execute function public.phase_template_validate_current_version();

create trigger phase_template_applications_immutable
before update or delete on public.phase_template_applications
for each row execute function public.phase_template_reject_immutable_change();

create trigger phase_template_audit_immutable
before update or delete on public.phase_template_audit
for each row execute function public.phase_template_protect_audit_change();

create function public.phase_template_protect_published_content()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_version_id bigint;
begin
  if tg_table_name = 'phase_template_stages' then
    v_version_id := case when tg_op = 'DELETE' then old.version_id else new.version_id end;
  else
    select stage.version_id into v_version_id
    from public.phase_template_stages stage
    where stage.id = case when tg_op = 'DELETE' then old.stage_id else new.stage_id end;
  end if;
  if exists (select 1 from public.phase_template_versions version where version.id = v_version_id and version.status <> 'DRAFT') then
    raise exception 'phase_template_published_content_immutable' using errcode = 'P0001';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger phase_template_stages_draft_only
before insert or update or delete on public.phase_template_stages
for each row execute function public.phase_template_protect_published_content();
create trigger phase_template_tasks_draft_only
before insert or update or delete on public.phase_template_tasks
for each row execute function public.phase_template_protect_published_content();

alter table public.phase_templates enable row level security;
alter table public.phase_template_versions enable row level security;
alter table public.phase_template_stages enable row level security;
alter table public.phase_template_tasks enable row level security;
alter table public.phase_template_applications enable row level security;
alter table public.phase_template_audit enable row level security;

create policy phase_templates_authorized_read on public.phase_templates for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and (
    public.has_permission('PHASE_TEMPLATE_MANAGE')
    or (status = 'ACTIVE' and current_version_id is not null and public.has_permission('PROJECT_MANAGE'))
  )
);
create policy phase_template_versions_authorized_read on public.phase_template_versions for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and (
    public.has_permission('PHASE_TEMPLATE_MANAGE')
    or (status = 'PUBLISHED' and public.has_permission('PROJECT_MANAGE') and exists (
      select 1 from public.phase_templates template
      where template.id = phase_template_versions.template_id
        and template.status = 'ACTIVE'
        and template.current_version_id = phase_template_versions.id
    ))
  )
);
create policy phase_template_stages_authorized_read on public.phase_template_stages for select to authenticated using (
  exists (select 1 from public.phase_template_versions version where version.id = phase_template_stages.version_id)
);
create policy phase_template_tasks_authorized_read on public.phase_template_tasks for select to authenticated using (
  exists (select 1 from public.phase_template_stages stage where stage.id = phase_template_tasks.stage_id)
);
create policy phase_template_applications_manager_read on public.phase_template_applications for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PHASE_TEMPLATE_MANAGE')
);
create policy phase_template_audit_manager_read on public.phase_template_audit for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PHASE_TEMPLATE_MANAGE')
);

revoke all on table public.phase_templates, public.phase_template_versions,
  public.phase_template_stages, public.phase_template_tasks,
  public.phase_template_applications, public.phase_template_audit
from public, anon, authenticated;
grant select on table public.phase_templates, public.phase_template_versions,
  public.phase_template_stages, public.phase_template_tasks,
  public.phase_template_applications, public.phase_template_audit
to authenticated;
revoke all on function public.phase_template_reject_immutable_change() from public, anon, authenticated;
revoke all on function public.phase_template_protect_audit_change() from public, anon, authenticated;
revoke all on function public.phase_template_protect_published_content() from public, anon, authenticated;
revoke all on function public.phase_template_validate_current_version() from public, anon, authenticated;

comment on table public.phase_templates is 'Release-one GENERAL project phase-template identities; empty seed catalog.';
comment on table public.phase_template_applications is 'Immutable project clone provenance; one application per project.';
comment on table public.phase_template_audit is 'Append-only phase-template audit retained for at least seven years.';

commit;
