-- Immutable monthly payroll settlement. Delivery only through the approved protected-main workflow.
begin;

do $$ begin
  if to_regclass('public.employees') is null or to_regclass('public.attendance') is null then raise exception 'Payroll precondition failed: employees/attendance missing'; end if;
  if to_regprocedure('public.current_employee_id()') is null or to_regprocedure('public.has_permission(text)') is null then raise exception 'Payroll authorization foundation missing'; end if;
end $$;

insert into public.permissions(code, description) values
 ('PAYROLL_VIEW','View payroll through authorized server capability'),
 ('PAYROLL_SETTLE','Create immutable monthly payroll settlements'),
 ('PAYROLL_ADJUST','Create approved payroll adjustments'),
 ('PAYROLL_CONFIGURE','Configure the first official settlement month')
on conflict (code) do nothing;

create table public.payroll_configuration (
  singleton boolean primary key default true check (singleton),
  first_settlement_month date not null check (first_settlement_month = date_trunc('month', first_settlement_month)::date),
  configured_by_employee_id bigint not null references public.employees(id) on delete restrict,
  configured_at timestamptz not null default now()
);

create table public.payroll_settlements (
  id uuid primary key default gen_random_uuid(), employee_id bigint not null references public.employees(id) on delete restrict,
  payroll_month date not null check (payroll_month = date_trunc('month', payroll_month)::date),
  worked_minutes integer not null check (worked_minutes >= 0), worked_hours numeric(10,2) not null check (worked_hours >= 0),
  calculated_shifts integer not null check (calculated_shifts >= 0), hourly_rate numeric(14,2) not null check (hourly_rate >= 0),
  base_salary numeric(14,2) not null, attendance_summary jsonb not null,
  settled_by_employee_id bigint not null references public.employees(id) on delete restrict,
  settled_at timestamptz not null default now(), created_at timestamptz not null default now(),
  unique(employee_id, payroll_month)
);

create table public.payroll_adjustments (
  id uuid primary key default gen_random_uuid(), settlement_id uuid not null references public.payroll_settlements(id) on delete restrict,
  revision_number integer not null check (revision_number > 0), amount numeric(14,2) not null check (amount <> 0),
  reason text not null check (length(btrim(reason)) >= 3), approved_by_employee_id bigint not null references public.employees(id) on delete restrict,
  approved_at timestamptz not null default now(), created_at timestamptz not null default now(), unique(settlement_id, revision_number)
);

create table public.payroll_audit_history (
  id bigint generated by default as identity primary key, event_type text not null check(event_type in ('CONFIGURED','SETTLED','ADJUSTED')),
  settlement_id uuid null references public.payroll_settlements(id) on delete restrict, employee_id bigint not null references public.employees(id) on delete restrict,
  actor_employee_id bigint not null references public.employees(id) on delete restrict, occurred_at timestamptz not null default now(), details jsonb not null default '{}'::jsonb
);

create or replace function public.block_immutable_payroll_change() returns trigger language plpgsql set search_path=public,pg_temp as $$ begin raise exception 'immutable payroll record cannot be changed'; end $$;
create trigger payroll_settlements_immutable before update or delete on public.payroll_settlements for each row execute function public.block_immutable_payroll_change();
create trigger payroll_adjustments_immutable before update or delete on public.payroll_adjustments for each row execute function public.block_immutable_payroll_change();
create trigger payroll_audit_immutable before update or delete on public.payroll_audit_history for each row execute function public.block_immutable_payroll_change();

create or replace function public.payroll_month_calculation(p_employee_id bigint, p_month date)
returns table(worked_minutes integer, worked_hours numeric, calculated_shifts integer, hourly_rate numeric, base_salary numeric, attendance_summary jsonb)
language sql stable security definer set search_path=public,auth,pg_temp as $$
 with rows as (
  select a.id, greatest(0, round(coalesce(a.total_hours,0)::numeric * 60))::integer minutes
  from public.attendance a where a.employee_id=p_employee_id and a.work_date >= date_trunc('month',p_month)::date and a.work_date < (date_trunc('month',p_month)+interval '1 month')::date and a.check_in is not null and a.check_out is not null
 ), totals as (select coalesce(sum(minutes),0)::integer mins, coalesce(sum(case when minutes<=0 then 0 when minutes<=180 then 1 when minutes<=360 then 2 else 3 end),0)::integer shifts, coalesce(jsonb_agg(jsonb_build_object('attendance_id',id,'worked_minutes',minutes) order by id),'[]'::jsonb) summary from rows)
 select t.mins, round(t.mins::numeric/60,2), t.shifts, coalesce(e.hourly_rate,0)::numeric, round(round(t.mins::numeric/60,2)*coalesce(e.hourly_rate,0)::numeric), t.summary from totals t join public.employees e on e.id=p_employee_id;
$$;

create or replace function public.configure_payroll_first_month(p_month date) returns void language plpgsql security definer set search_path=public,auth,pg_temp as $$ declare actor bigint:=public.current_employee_id(); begin
 if actor is null or not public.has_permission('PAYROLL_CONFIGURE') then raise exception 'payroll configuration forbidden' using errcode='42501'; end if;
 if p_month <> date_trunc('month',p_month)::date then raise exception 'month must be first day'; end if;
 insert into public.payroll_configuration(singleton,first_settlement_month,configured_by_employee_id,configured_at) values(true,p_month,actor,now());
 insert into public.payroll_audit_history(event_type,employee_id,actor_employee_id,details) values('CONFIGURED',actor,actor,jsonb_build_object('first_settlement_month',p_month));
end $$;

create or replace function public.settle_monthly_payroll(p_employee_id bigint,p_month date) returns uuid language plpgsql security definer set search_path=public,auth,pg_temp as $$ declare actor bigint:=public.current_employee_id(); config_month date; calc record; result uuid; stamp timestamptz:=clock_timestamp(); begin
 if actor is null or not public.has_permission('PAYROLL_SETTLE') then raise exception 'payroll settlement forbidden' using errcode='42501'; end if;
 select first_settlement_month into config_month from public.payroll_configuration where singleton=true;
 if config_month is null then raise exception 'first settlement month is not configured'; end if;
 if p_month < config_month then raise exception 'historical settlement is not allowed'; end if;
 select * into calc from public.payroll_month_calculation(p_employee_id,p_month);
 insert into public.payroll_settlements(employee_id,payroll_month,worked_minutes,worked_hours,calculated_shifts,hourly_rate,base_salary,attendance_summary,settled_by_employee_id,settled_at,created_at)
 values(p_employee_id,p_month,calc.worked_minutes,calc.worked_hours,calc.calculated_shifts,calc.hourly_rate,calc.base_salary,calc.attendance_summary,actor,stamp,stamp) returning id into result;
 insert into public.payroll_audit_history(event_type,settlement_id,employee_id,actor_employee_id,occurred_at,details) values('SETTLED',result,p_employee_id,actor,stamp,jsonb_build_object('base_salary',calc.base_salary)); return result;
end $$;

create or replace function public.create_payroll_adjustment(p_settlement_id uuid,p_amount numeric,p_reason text) returns uuid language plpgsql security definer set search_path=public,auth,pg_temp as $$ declare actor bigint:=public.current_employee_id(); employee bigint; result uuid; stamp timestamptz:=clock_timestamp(); revision integer; begin
 if actor is null or not public.has_permission('PAYROLL_ADJUST') then raise exception 'payroll adjustment forbidden' using errcode='42501'; end if;
 if p_amount=0 or length(btrim(p_reason))<3 then raise exception 'invalid adjustment'; end if;
 select employee_id into employee from public.payroll_settlements where id=p_settlement_id; if employee is null then raise exception 'settlement not found'; end if;
 select coalesce(max(revision_number),0)+1 into revision from public.payroll_adjustments where settlement_id=p_settlement_id;
 insert into public.payroll_adjustments(settlement_id,revision_number,amount,reason,approved_by_employee_id,approved_at,created_at) values(p_settlement_id,revision,p_amount,btrim(p_reason),actor,stamp,stamp) returning id into result;
 insert into public.payroll_audit_history(event_type,settlement_id,employee_id,actor_employee_id,occurred_at,details) values('ADJUSTED',p_settlement_id,employee,actor,stamp,jsonb_build_object('adjustment_id',result,'amount',p_amount,'reason',btrim(p_reason))); return result;
end $$;

create type public.payroll_result_row as (employee_id bigint,employee_name text,payroll_month date,worked_minutes integer,worked_hours numeric,calculated_shifts integer,hourly_rate numeric,base_salary numeric,settlement_id uuid,settled_at timestamptz,approved_adjustments jsonb,adjustment_total numeric,final_payable_amount numeric);

create or replace function public.payroll_result(p_month date,p_employee_id bigint)
returns setof public.payroll_result_row
language sql stable security definer set search_path=public,auth,pg_temp as $$
 select e.id,e.full_name,date_trunc('month',p_month)::date,coalesce(s.worked_minutes,c.worked_minutes),coalesce(s.worked_hours,c.worked_hours),coalesce(s.calculated_shifts,c.calculated_shifts),coalesce(s.hourly_rate,c.hourly_rate),coalesce(s.base_salary,c.base_salary),s.id,s.settled_at,
 coalesce((select jsonb_agg(jsonb_build_object('id',a.id,'amount',a.amount,'reason',a.reason,'approved_at',a.approved_at) order by a.revision_number) from public.payroll_adjustments a where a.settlement_id=s.id),'[]'::jsonb),
 coalesce((select sum(a.amount) from public.payroll_adjustments a where a.settlement_id=s.id),0),coalesce(s.base_salary,c.base_salary)+coalesce((select sum(a.amount) from public.payroll_adjustments a where a.settlement_id=s.id),0)
 from public.employees e cross join lateral public.payroll_month_calculation(e.id,p_month)c left join public.payroll_settlements s on s.employee_id=e.id and s.payroll_month=date_trunc('month',p_month)::date where e.id=p_employee_id;
$$;
create or replace function public.get_my_monthly_payroll(p_month date) returns setof public.payroll_result_row language sql stable security definer set search_path=public,auth,pg_temp as $$ select * from public.payroll_result(p_month,public.current_employee_id()) where public.has_workspace_access('STAFF_WORKSPACE'); $$;
create or replace function public.list_monthly_payroll_for_admin(p_month date) returns setof public.payroll_result_row language sql stable security definer set search_path=public,auth,pg_temp as $$ select r.* from public.employees e cross join lateral public.payroll_result(p_month,e.id) r where public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PAYROLL_VIEW') and e.status='ACTIVE' and coalesce(e.is_active,true); $$;

alter table public.payroll_configuration enable row level security; alter table public.payroll_settlements enable row level security; alter table public.payroll_adjustments enable row level security; alter table public.payroll_audit_history enable row level security;
create policy "payroll own settlement select" on public.payroll_settlements for select to authenticated using(employee_id=public.current_employee_id() and public.has_workspace_access('STAFF_WORKSPACE'));
create policy "payroll admin settlement select" on public.payroll_settlements for select to authenticated using(public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PAYROLL_VIEW'));
create policy "payroll own adjustment select" on public.payroll_adjustments for select to authenticated using(exists(select 1 from public.payroll_settlements s where s.id=settlement_id and s.employee_id=public.current_employee_id()) and public.has_workspace_access('STAFF_WORKSPACE'));
create policy "payroll admin adjustment select" on public.payroll_adjustments for select to authenticated using(public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PAYROLL_VIEW'));
create policy "payroll admin audit select" on public.payroll_audit_history for select to authenticated using(public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PAYROLL_VIEW'));
revoke all on public.payroll_configuration,public.payroll_settlements,public.payroll_adjustments,public.payroll_audit_history from anon,authenticated;
grant select on public.payroll_settlements,public.payroll_adjustments to authenticated; grant select on public.payroll_audit_history to authenticated;
revoke all on function public.payroll_month_calculation(bigint,date),public.payroll_result(date,bigint),public.get_my_monthly_payroll(date),public.list_monthly_payroll_for_admin(date),public.configure_payroll_first_month(date),public.settle_monthly_payroll(bigint,date),public.create_payroll_adjustment(uuid,numeric,text) from public,anon;
grant execute on function public.get_my_monthly_payroll(date),public.list_monthly_payroll_for_admin(date),public.configure_payroll_first_month(date),public.settle_monthly_payroll(bigint,date),public.create_payroll_adjustment(uuid,numeric,text) to authenticated;
commit;
