-- Audited attendance cancellation foundation. Delivery only through protected main.
begin;

do $$
begin
  if to_regclass('public.attendance') is null
    or to_regclass('public.employees') is null
    or to_regclass('public.payroll_settlements') is null then
    raise exception 'Attendance cancellation precondition failed: required relation missing';
  end if;
end $$;

alter table public.attendance
  add column cancellation_reason text null,
  add column cancelled_by_employee_id bigint null references public.employees(id) on delete restrict,
  add column cancelled_at timestamptz null,
  add constraint attendance_cancellation_metadata_complete check (
    (cancelled_at is not null
      and check_out is null
      and total_hours is null
      and total_salary is null
      and length(btrim(cancellation_reason)) >= 10
      and cancelled_by_employee_id is not null)
    or
    (cancelled_at is null
      and cancellation_reason is null
      and cancelled_by_employee_id is null)
  );

create table public.attendance_cancellation_audit (
  id bigint generated by default as identity primary key,
  attendance_id bigint not null,
  employee_id bigint not null references public.employees(id) on delete restrict,
  event_type text not null check (event_type in ('CANCELLED', 'ROLLBACK_RESTORED')),
  previous_status text null,
  resulting_status text null,
  reason text not null check (length(btrim(reason)) >= 10),
  actor_employee_id bigint not null references public.employees(id) on delete restrict,
  occurred_at timestamptz not null,
  cancellation_event_id bigint null references public.attendance_cancellation_audit(id) on delete restrict,
  details jsonb not null default '{}'::jsonb
);

create or replace function public.block_attendance_cancellation_audit_change()
returns trigger language plpgsql set search_path = public, pg_temp as $$
begin
  raise exception 'attendance cancellation audit history is immutable';
end $$;

create trigger attendance_cancellation_audit_immutable
before update or delete on public.attendance_cancellation_audit
for each row execute function public.block_attendance_cancellation_audit_change();

alter table public.attendance_cancellation_audit enable row level security;
revoke all on public.attendance_cancellation_audit from public, anon, authenticated;
grant select on public.attendance_cancellation_audit to authenticated;
create policy "attendance cancellation audit admin select"
on public.attendance_cancellation_audit for select to authenticated
using (
  public.has_workspace_access('ADMIN_WORKSPACE')
  and public.has_permission('ATTENDANCE_VIEW')
);

create or replace function public.payroll_month_calculation(p_employee_id bigint, p_month date)
returns table(worked_minutes integer, worked_hours numeric, calculated_shifts integer, hourly_rate numeric, base_salary numeric, attendance_summary jsonb)
language sql stable security definer set search_path=public,auth,pg_temp as $$
 with rows as (
  select a.id, greatest(0, round(coalesce(a.total_hours,0)::numeric * 60))::integer minutes
  from public.attendance a
  where a.employee_id=p_employee_id
    and a.work_date >= date_trunc('month',p_month)::date
    and a.work_date < (date_trunc('month',p_month)+interval '1 month')::date
    and a.check_in is not null
    and a.check_out is not null
    and a.cancelled_at is null
 ), totals as (select coalesce(sum(minutes),0)::integer mins, coalesce(sum(case when minutes<=0 then 0 when minutes<=180 then 1 when minutes<=360 then 2 else 3 end),0)::integer shifts, coalesce(jsonb_agg(jsonb_build_object('attendance_id',id,'worked_minutes',minutes) order by id),'[]'::jsonb) summary from rows)
 select t.mins, round(t.mins::numeric/60,2), t.shifts, coalesce(e.hourly_rate,0)::numeric, round(round(t.mins::numeric/60,2)*coalesce(e.hourly_rate,0)::numeric), t.summary from totals t join public.employees e on e.id=p_employee_id;
$$;

revoke all on function public.payroll_month_calculation(bigint,date) from public, anon, authenticated;

comment on table public.attendance_cancellation_audit is
  'Immutable operator audit history for explicit attendance cancellation and rollback.';

commit;
