-- Promoted from the reviewed Phase Status/Dependency forward package.
-- Production delivery is owned by the Supabase GitHub Integration after merge to protected main.

begin;

-- Precondition checks intentionally fail fast before schema mutation.
do $$
begin
  if to_regclass('public.projects') is null then
    raise exception 'Precondition failed: public.projects does not exist.';
  end if;
  if to_regclass('public.phases') is null then
    raise exception 'Precondition failed: public.phases does not exist.';
  end if;
  if to_regclass('public.employees') is null then
    raise exception 'Precondition failed: public.employees does not exist.';
  end if;
  if to_regprocedure('public.can_view_project(bigint)') is null then
    raise exception 'Precondition failed: public.can_view_project(bigint) does not exist.';
  end if;
  if exists (select 1 from public.phases where project_id is null) then
    raise exception 'Precondition failed: public.phases has null project_id rows.';
  end if;
  if exists (
    select 1 from public.phases phase
    left join public.projects project on project.id = phase.project_id
    where project.id is null
  ) then
    raise exception 'Precondition failed: public.phases has orphan project rows.';
  end if;
  if exists (
    select 1 from public.phases group by project_id, order_index having count(*) > 1
  ) then
    raise exception 'Precondition failed: duplicate phase order_index within a project.';
  end if;
  if exists (
    select 1 from public.phases
    where status is not null
      and status not in ('NOT_STARTED', 'IN_PROGRESS', 'ACTIVE', 'LOCKED', 'COMPLETED', 'BLOCKED', 'REVIEW', 'CANCELLED')
  ) then
    raise exception 'Precondition failed: public.phases contains an unapproved status.';
  end if;
end $$;

alter table public.phases
  add column if not exists status text,
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz,
  add column if not exists updated_by_employee_id bigint;

update public.phases
set status = case
  when completed_at is not null then 'COMPLETED'
  when status = 'IN_PROGRESS' then 'ACTIVE'
  when order_index = 0 then 'ACTIVE'
  else 'LOCKED'
end
where status is null or status in ('NOT_STARTED', 'IN_PROGRESS');

update public.phases
set updated_at = now()
where updated_at is null;

alter table public.phases
  alter column status set default 'LOCKED',
  alter column status set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

do $$
begin
  alter table public.phases drop constraint if exists phases_status_check;
  alter table public.phases
    add constraint phases_status_check
    check (status in ('ACTIVE', 'LOCKED', 'COMPLETED', 'BLOCKED', 'REVIEW', 'CANCELLED'));

  if not exists (
    select 1 from pg_constraint
    where conname = 'phases_updated_by_employee_id_fkey'
      and conrelid = 'public.phases'::regclass
  ) then
    alter table public.phases
      add constraint phases_updated_by_employee_id_fkey
      foreign key (updated_by_employee_id)
      references public.employees(id)
      on update cascade
      on delete set null;
  end if;
end $$;

create table if not exists public.phase_status_history (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on update cascade on delete cascade,
  phase_id bigint not null references public.phases(id) on update cascade on delete cascade,
  actor_employee_id bigint not null references public.employees(id) on update cascade on delete restrict,
  action text not null,
  old_status text,
  new_status text not null,
  reason text not null,
  note text,
  override_flag boolean not null default false,
  created_at timestamptz not null default now(),
  constraint phase_status_history_action_check check (action in ('COMPLETE', 'LOCK', 'UNLOCK', 'REOPEN', 'SKIP', 'CANCEL', 'OVERRIDE_LOCK')),
  constraint phase_status_history_new_status_check check (new_status in ('ACTIVE', 'LOCKED', 'COMPLETED', 'BLOCKED', 'REVIEW', 'CANCELLED')),
  constraint phase_status_history_reason_check check (length(btrim(reason)) > 0)
);

create index if not exists phases_project_order_idx on public.phases(project_id, order_index);
create index if not exists phases_project_status_idx on public.phases(project_id, status);
create index if not exists phase_status_history_project_phase_created_idx on public.phase_status_history(project_id, phase_id, created_at desc);

create or replace function public.transition_project_phase_status(
  p_project_id bigint,
  p_phase_id bigint,
  p_actor_employee_id bigint,
  p_action text,
  p_old_status text,
  p_new_status text,
  p_reason text,
  p_note text default null,
  p_override_flag boolean default false
)
returns table (phase_id bigint, phase_status text)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_current_status text;
begin
  if p_action not in ('COMPLETE', 'LOCK', 'UNLOCK', 'REOPEN', 'SKIP', 'CANCEL', 'OVERRIDE_LOCK') then
    raise exception 'Unsupported phase action.';
  end if;
  if p_new_status not in ('ACTIVE', 'LOCKED', 'COMPLETED', 'BLOCKED', 'REVIEW', 'CANCELLED') then
    raise exception 'Unsupported target phase status.';
  end if;
  if nullif(btrim(p_reason), '') is null then
    raise exception 'Phase transition reason is required.';
  end if;
  if not exists (select 1 from public.employees where id = p_actor_employee_id) then
    raise exception 'Phase transition actor does not exist.';
  end if;

  select phase.status
  into v_current_status
  from public.phases phase
  where phase.id = p_phase_id
    and phase.project_id = p_project_id
  for update;

  if not found then
    raise exception 'Phase does not belong to project.';
  end if;
  if v_current_status is distinct from p_old_status then
    raise exception 'Phase status changed concurrently.';
  end if;

  update public.phases
  set status = p_new_status,
      completed_at = case when p_new_status = 'COMPLETED' then coalesce(completed_at, now()) else null end,
      updated_at = now(),
      updated_by_employee_id = p_actor_employee_id
  where id = p_phase_id
    and project_id = p_project_id;

  insert into public.phase_status_history (
    project_id, phase_id, actor_employee_id, action, old_status, new_status,
    reason, note, override_flag
  ) values (
    p_project_id, p_phase_id, p_actor_employee_id, p_action, v_current_status, p_new_status,
    btrim(p_reason), nullif(btrim(p_note), ''), p_override_flag
  );

  return query select p_phase_id, p_new_status;
end;
$$;

alter function public.transition_project_phase_status(bigint, bigint, bigint, text, text, text, text, text, boolean) owner to postgres;
revoke all on function public.transition_project_phase_status(bigint, bigint, bigint, text, text, text, text, text, boolean) from public, anon, authenticated;
grant execute on function public.transition_project_phase_status(bigint, bigint, bigint, text, text, text, text, text, boolean) to service_role;

alter table public.phase_status_history enable row level security;

revoke all on public.phase_status_history from public, anon, authenticated;
grant select on public.phase_status_history to authenticated;

drop policy if exists "phase status history project view select" on public.phase_status_history;
create policy "phase status history project view select"
  on public.phase_status_history
  for select
  to authenticated
  using (public.can_view_project(project_id));

commit;
