-- Phase Template release one.
-- Approved production migration; empty catalog by design.
-- Adds schema, RLS, lifecycle RPC, and atomic project-template application.

begin;

select pg_advisory_xact_lock(hashtextextended('luminal:phase-template:v1', 0));

insert into public.permissions (code, description)
values ('PHASE_TEMPLATE_MANAGE', 'Manage project phase templates and version history')
on conflict (code) do update set description = excluded.description;

alter table public.projects add column start_date date null;
alter table public.projects
  add constraint projects_start_date_before_deadline_check
  check (start_date is null or project_deadline is null or start_date <= project_deadline);
comment on column public.projects.start_date is
  'Canonical project calendar anchor; required only when a Phase Template is applied.';

alter table public.tasks add column is_required boolean null;
alter table public.tasks add column requires_review boolean null;
comment on column public.tasks.is_required is
  'Template-derived task requirement; NULL preserves legacy/unspecified semantics.';
comment on column public.tasks.requires_review is
  'Template-derived review requirement; NULL preserves legacy/unspecified semantics.';

create table public.phase_templates (
  id bigint generated by default as identity primary key,
  name text not null,
  normalized_name text generated always as (lower(btrim(name))) stored,
  description text null,
  project_type text not null default 'GENERAL',
  status text not null default 'ACTIVE',
  current_version_id bigint null,
  created_by_employee_id bigint not null references public.employees(id) on delete restrict,
  updated_by_employee_id bigint not null references public.employees(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint phase_templates_name_not_blank check (length(btrim(name)) > 0),
  constraint phase_templates_project_type_check check (project_type = 'GENERAL'),
  constraint phase_templates_status_check check (status in ('ACTIVE', 'ARCHIVED')),
  constraint phase_templates_normalized_name_unique unique (project_type, normalized_name)
);

create table public.phase_template_versions (
  id bigint generated by default as identity primary key,
  template_id bigint not null references public.phase_templates(id) on delete restrict,
  version_number integer not null,
  status text not null default 'DRAFT',
  source_version_id bigint null references public.phase_template_versions(id) on delete restrict,
  published_at timestamptz null,
  archived_at timestamptz null,
  created_by_employee_id bigint not null references public.employees(id) on delete restrict,
  updated_by_employee_id bigint not null references public.employees(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint phase_template_versions_number_positive check (version_number > 0),
  constraint phase_template_versions_status_check check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  constraint phase_template_versions_lifecycle_check check (
    (status = 'DRAFT' and published_at is null and archived_at is null)
    or (status = 'PUBLISHED' and published_at is not null and archived_at is null)
    or (status = 'ARCHIVED' and archived_at is not null)
  ),
  constraint phase_template_versions_template_number_unique unique (template_id, version_number)
);

alter table public.phase_templates
  add constraint phase_templates_current_version_id_fkey
  foreign key (current_version_id) references public.phase_template_versions(id) on delete restrict;

create unique index phase_template_versions_one_draft_idx
  on public.phase_template_versions(template_id) where status = 'DRAFT';
create unique index phase_template_versions_one_published_idx
  on public.phase_template_versions(template_id) where status = 'PUBLISHED';
create index phase_template_versions_source_version_idx
  on public.phase_template_versions(source_version_id) where source_version_id is not null;

create table public.phase_template_stages (
  id bigint generated by default as identity primary key,
  version_id bigint not null references public.phase_template_versions(id) on delete restrict,
  name text not null,
  normalized_name text generated always as (lower(btrim(name))) stored,
  order_index integer not null,
  start_offset_days integer null,
  duration_days integer null,
  requires_review boolean not null default false,
  created_at timestamptz not null default now(),
  constraint phase_template_stages_name_not_blank check (length(btrim(name)) > 0),
  constraint phase_template_stages_order_positive check (order_index > 0),
  constraint phase_template_stages_offsets_nonnegative check (start_offset_days >= 0 and duration_days >= 0),
  constraint phase_template_stages_version_order_unique unique (version_id, order_index),
  constraint phase_template_stages_version_name_unique unique (version_id, normalized_name)
);

create table public.phase_template_tasks (
  id bigint generated by default as identity primary key,
  stage_id bigint not null references public.phase_template_stages(id) on delete restrict,
  name text not null,
  normalized_name text generated always as (lower(btrim(name))) stored,
  description text null,
  order_index integer not null,
  start_offset_days integer null,
  is_required boolean not null default true,
  requires_review boolean not null default false,
  assignee_role_code text null,
  created_at timestamptz not null default now(),
  constraint phase_template_tasks_name_not_blank check (length(btrim(name)) > 0),
  constraint phase_template_tasks_order_positive check (order_index > 0),
  constraint phase_template_tasks_offset_nonnegative check (start_offset_days >= 0),
  constraint phase_template_tasks_role_check check (
    assignee_role_code is null or assignee_role_code in (
      'PROJECT_OWNER', 'PROJECT_MANAGER', 'CREATIVE_LEAD', 'CONTRIBUTOR'
    )
  ),
  constraint phase_template_tasks_stage_order_unique unique (stage_id, order_index),
  constraint phase_template_tasks_stage_name_unique unique (stage_id, normalized_name)
);

create table public.phase_template_applications (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete restrict,
  template_id bigint not null references public.phase_templates(id) on delete restrict,
  version_id bigint not null references public.phase_template_versions(id) on delete restrict,
  applied_by_employee_id bigint not null references public.employees(id) on delete restrict,
  applied_at timestamptz not null default now(),
  clone_summary jsonb not null default '{}'::jsonb,
  constraint phase_template_applications_project_unique unique (project_id),
  constraint phase_template_applications_summary_object check (jsonb_typeof(clone_summary) = 'object')
);

create table public.phase_template_audit (
  id bigint generated by default as identity primary key,
  template_id bigint null references public.phase_templates(id) on delete set null,
  version_id bigint null references public.phase_template_versions(id) on delete set null,
  actor_employee_id bigint not null references public.employees(id) on delete restrict,
  action text not null,
  reason text null,
  before_data jsonb null,
  after_data jsonb null,
  occurred_at timestamptz not null default now(),
  retain_until date generated always as ((occurred_at at time zone 'UTC')::date + 2557) stored,
  constraint phase_template_audit_action_check check (action in (
    'DRAFT_CREATED', 'DRAFT_UPDATED', 'VERSION_CLONED', 'PUBLISHED',
    'ARCHIVED', 'RESTORED', 'DRAFT_DELETED', 'APPLIED'
  )),
  constraint phase_template_audit_reason_check check (
    action not in ('PUBLISHED', 'ARCHIVED', 'RESTORED', 'DRAFT_DELETED')
    or coalesce(length(btrim(reason)), 0) > 0
  ),
  constraint phase_template_audit_before_object check (before_data is null or jsonb_typeof(before_data) = 'object'),
  constraint phase_template_audit_after_object check (after_data is null or jsonb_typeof(after_data) = 'object')
);

create index phase_template_stages_version_idx on public.phase_template_stages(version_id);
create index phase_template_tasks_stage_idx on public.phase_template_tasks(stage_id);
create index phase_template_applications_template_idx on public.phase_template_applications(template_id);
create index phase_template_applications_version_idx on public.phase_template_applications(version_id);
create index phase_template_applications_actor_idx on public.phase_template_applications(applied_by_employee_id);
create index phase_template_audit_template_time_idx on public.phase_template_audit(template_id, occurred_at desc);
create index phase_template_audit_version_idx on public.phase_template_audit(version_id) where version_id is not null;
create index phase_template_audit_actor_idx on public.phase_template_audit(actor_employee_id);
create index phase_template_audit_retention_idx on public.phase_template_audit(retain_until);

create function public.phase_template_reject_immutable_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'phase_template_immutable_row' using errcode = 'P0001';
end;
$$;

create function public.phase_template_protect_audit_change()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE'
    and old.version_id is not null and new.version_id is null
    and new.id = old.id
    and new.template_id is not distinct from old.template_id
    and new.actor_employee_id = old.actor_employee_id
    and new.action = old.action
    and new.reason is not distinct from old.reason
    and new.before_data is not distinct from old.before_data
    and new.after_data is not distinct from old.after_data
    and new.occurred_at = old.occurred_at
    and new.retain_until = old.retain_until then
    return new;
  end if;
  raise exception 'phase_template_audit_immutable_row' using errcode = 'P0001';
end;
$$;

create function public.phase_template_validate_current_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.current_version_id is not null and not exists (
    select 1
    from public.phase_template_versions version
    where version.id = new.current_version_id
      and version.template_id = new.id
      and version.status = 'PUBLISHED'
  ) then
    raise exception 'phase_template_current_version_invalid' using errcode = '23514';
  end if;
  return new;
end;
$$;

create trigger phase_templates_current_version_guard
before insert or update of current_version_id on public.phase_templates
for each row execute function public.phase_template_validate_current_version();

create trigger phase_template_applications_immutable
before update or delete on public.phase_template_applications
for each row execute function public.phase_template_reject_immutable_change();

create trigger phase_template_audit_immutable
before update or delete on public.phase_template_audit
for each row execute function public.phase_template_protect_audit_change();

create function public.phase_template_protect_published_content()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_version_id bigint;
begin
  if tg_table_name = 'phase_template_stages' then
    v_version_id := case when tg_op = 'DELETE' then old.version_id else new.version_id end;
  else
    select stage.version_id into v_version_id
    from public.phase_template_stages stage
    where stage.id = case when tg_op = 'DELETE' then old.stage_id else new.stage_id end;
  end if;
  if exists (select 1 from public.phase_template_versions version where version.id = v_version_id and version.status <> 'DRAFT') then
    raise exception 'phase_template_published_content_immutable' using errcode = 'P0001';
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

create trigger phase_template_stages_draft_only
before insert or update or delete on public.phase_template_stages
for each row execute function public.phase_template_protect_published_content();
create trigger phase_template_tasks_draft_only
before insert or update or delete on public.phase_template_tasks
for each row execute function public.phase_template_protect_published_content();

alter table public.phase_templates enable row level security;
alter table public.phase_template_versions enable row level security;
alter table public.phase_template_stages enable row level security;
alter table public.phase_template_tasks enable row level security;
alter table public.phase_template_applications enable row level security;
alter table public.phase_template_audit enable row level security;

create policy phase_templates_authorized_read on public.phase_templates for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and (
    public.has_permission('PHASE_TEMPLATE_MANAGE')
    or (status = 'ACTIVE' and current_version_id is not null and public.has_permission('PROJECT_MANAGE'))
  )
);
create policy phase_template_versions_authorized_read on public.phase_template_versions for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and (
    public.has_permission('PHASE_TEMPLATE_MANAGE')
    or (status = 'PUBLISHED' and public.has_permission('PROJECT_MANAGE') and exists (
      select 1 from public.phase_templates template
      where template.id = phase_template_versions.template_id
        and template.status = 'ACTIVE'
        and template.current_version_id = phase_template_versions.id
    ))
  )
);
create policy phase_template_stages_authorized_read on public.phase_template_stages for select to authenticated using (
  exists (select 1 from public.phase_template_versions version where version.id = phase_template_stages.version_id)
);
create policy phase_template_tasks_authorized_read on public.phase_template_tasks for select to authenticated using (
  exists (select 1 from public.phase_template_stages stage where stage.id = phase_template_tasks.stage_id)
);
create policy phase_template_applications_manager_read on public.phase_template_applications for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PHASE_TEMPLATE_MANAGE')
);
create policy phase_template_audit_manager_read on public.phase_template_audit for select to authenticated using (
  public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PHASE_TEMPLATE_MANAGE')
);

revoke all on table public.phase_templates, public.phase_template_versions,
  public.phase_template_stages, public.phase_template_tasks,
  public.phase_template_applications, public.phase_template_audit
from public, anon, authenticated;
grant select on table public.phase_templates, public.phase_template_versions,
  public.phase_template_stages, public.phase_template_tasks,
  public.phase_template_applications, public.phase_template_audit
to authenticated;
revoke all on function public.phase_template_reject_immutable_change() from public, anon, authenticated;
revoke all on function public.phase_template_protect_audit_change() from public, anon, authenticated;
revoke all on function public.phase_template_protect_published_content() from public, anon, authenticated;
revoke all on function public.phase_template_validate_current_version() from public, anon, authenticated;

comment on table public.phase_templates is 'Release-one GENERAL project phase-template identities; empty seed catalog.';
comment on table public.phase_template_applications is 'Immutable project clone provenance; one application per project.';
comment on table public.phase_template_audit is 'Append-only phase-template audit retained for at least seven years.';

do $$
begin
  if to_regprocedure('public.create_project_atomic(jsonb)') is null then
    raise exception 'Phase Template stopped: create_project_atomic(jsonb) is missing.';
  end if;
  if md5(pg_get_functiondef('public.create_project_atomic(jsonb)'::regprocedure))
     <> 'f893db4f9c021120ea697badda853cb9' then
    raise exception 'Phase Template stopped: live create_project_atomic(jsonb) baseline changed.';
  end if;
end $$;

create or replace function public.create_project_atomic(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_employee_id bigint;
  v_manager_employee_id bigint;
  v_project_name text;
  v_project_code text;
  v_status text;
  v_start_date date;
  v_deadline date;
  v_project_id bigint;
  v_phase jsonb;
  v_phase_id bigint;
  v_task jsonb;
  v_task_id bigint;
  v_subtask jsonb;
  v_subtask_id bigint;
  v_assignee bigint;
  v_assignee_name text;
  v_task_status text;
  v_note text;
  v_phase_map jsonb := '{}'::jsonb;
  v_task_map jsonb := '{}'::jsonb;
  v_task_key text;
  v_template_id bigint;
  v_template_version_id bigint;
  v_template_stage record;
  v_template_task record;
  v_template_stage_count integer := 0;
  v_template_task_count integer := 0;
  v_unassigned_task_count integer := 0;
  v_phase_start date;
  v_phase_end date;
  v_task_deadline date;
begin
  if v_actor is null then
    return jsonb_build_object('success', false, 'code', 'session_not_verified', 'message', 'Phiên đăng nhập không hợp lệ.');
  end if;

  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Dữ liệu dự án không hợp lệ.');
  end if;

  select employee.id into v_employee_id
  from public.employees employee
  where employee.auth_user_id = v_actor
    and coalesce(employee.is_active, true) = true
    and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
  limit 1;

  if v_employee_id is null then
    return jsonb_build_object('success', false, 'code', 'actor_not_allowed', 'message', 'Không thể xác định nhân sự thao tác.');
  end if;

  if not (public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PROJECT_MANAGE')) then
    return jsonb_build_object('success', false, 'code', 'permission_forbidden', 'message', 'Bạn không có quyền tạo dự án.');
  end if;

  if p_payload ? 'actorEmployeeId'
    or p_payload ? 'actor_employee_id'
    or p_payload ? 'createdByEmployeeId'
    or p_payload ? 'appliedByEmployeeId' then
    return jsonb_build_object('success', false, 'code', 'client_actor_rejected', 'message', 'Dữ liệu người thao tác không hợp lệ.');
  end if;

  v_project_name := nullif(btrim(coalesce(p_payload->>'projectName', p_payload->>'project_name')), '');
  v_project_code := upper(nullif(btrim(coalesce(p_payload->>'projectCode', p_payload->>'project_code')), ''));
  v_status := upper(nullif(btrim(coalesce(p_payload->>'status', 'PROCESSING')), ''));
  v_manager_employee_id := nullif(p_payload->>'managerEmployeeId', '')::bigint;
  v_template_version_id := nullif(p_payload->>'templateVersionId', '')::bigint;
  v_start_date := nullif(p_payload->>'startDate', '')::date;
  v_deadline := nullif(p_payload->>'projectDeadline', '')::date;

  if v_project_name is null then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Vui lòng nhập tên dự án.');
  end if;
  if v_project_code is null then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Vui lòng nhập mã dự án duy nhất.');
  end if;
  if v_status not in ('DRAFT','PLANNING','PROCESSING','IN_PROGRESS','BLOCKED','ON_HOLD','COMPLETED','ARCHIVED','CANCELLED') then
    return jsonb_build_object('success', false, 'code', 'invalid_project_status', 'message', 'Trạng thái dự án không hợp lệ.');
  end if;
  if v_manager_employee_id is null or not exists (
    select 1 from public.employees employee
    where employee.id = v_manager_employee_id
      and coalesce(employee.is_active, true) = true
      and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
  ) then
    return jsonb_build_object('success', false, 'code', 'invalid_manager', 'message', 'Người phụ trách không còn hoạt động.');
  end if;
  if v_start_date is not null and v_deadline is not null and v_start_date > v_deadline then
    return jsonb_build_object('success', false, 'code', 'invalid_date_order', 'message', 'Ngày bắt đầu không được sau hạn hoàn thành.');
  end if;

  if jsonb_typeof(coalesce(p_payload->'memberEmployeeIds', '[]'::jsonb)) <> 'array'
    or jsonb_typeof(coalesce(p_payload->'phases', '[]'::jsonb)) <> 'array'
    or jsonb_typeof(coalesce(p_payload->'tasks', '[]'::jsonb)) <> 'array' then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Danh sách dự án không hợp lệ.');
  end if;

  for v_assignee in
    select jsonb_array_elements_text(coalesce(p_payload->'memberEmployeeIds', '[]'::jsonb))::bigint
  loop
    if not exists (
      select 1 from public.employees employee
      where employee.id = v_assignee
        and coalesce(employee.is_active, true) = true
        and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
    ) then
      return jsonb_build_object('success', false, 'code', 'invalid_member', 'message', 'Thành viên dự án không hợp lệ.');
    end if;
  end loop;

  if v_template_version_id is not null then
    if v_start_date is null then
      return jsonb_build_object('success', false, 'code', 'template_start_date_required', 'message', 'Vui lòng chọn ngày bắt đầu khi dùng mẫu giai đoạn.');
    end if;
    if v_deadline is null then
      return jsonb_build_object('success', false, 'code', 'template_deadline_required', 'message', 'Vui lòng chọn hạn hoàn thành khi dùng mẫu giai đoạn.');
    end if;
    if jsonb_array_length(coalesce(p_payload->'phases', '[]'::jsonb)) > 0
      or jsonb_array_length(coalesce(p_payload->'tasks', '[]'::jsonb)) > 0 then
      return jsonb_build_object('success', false, 'code', 'template_custom_workflow_conflict', 'message', 'Không thể dùng đồng thời mẫu và quy trình tùy chỉnh.');
    end if;

    select template.id into v_template_id
    from public.phase_template_versions version
    join public.phase_templates template on template.id = version.template_id
    where version.id = v_template_version_id
      and version.status = 'PUBLISHED'
      and template.status = 'ACTIVE'
      and template.project_type = 'GENERAL'
      and template.current_version_id = version.id
    for update of version, template;

    if v_template_id is null then
      return jsonb_build_object('success', false, 'code', 'template_version_not_current', 'message', 'Mẫu giai đoạn không còn hiệu lực.');
    end if;

    select count(*), min(stage.order_index), max(stage.order_index)
      into v_template_stage_count, v_assignee, v_phase_id
    from public.phase_template_stages stage
    where stage.version_id = v_template_version_id;

    if v_template_stage_count = 0 or v_assignee <> 1 or v_phase_id <> v_template_stage_count then
      return jsonb_build_object('success', false, 'code', 'template_stage_order_invalid', 'message', 'Thứ tự giai đoạn trong mẫu không hợp lệ.');
    end if;

    if exists (
      select 1
      from public.phase_template_tasks task
      join public.phase_template_stages stage on stage.id = task.stage_id
      where stage.version_id = v_template_version_id
      group by task.stage_id
      having min(task.order_index) <> 1 or max(task.order_index) <> count(*)
    ) then
      return jsonb_build_object('success', false, 'code', 'template_task_order_invalid', 'message', 'Thứ tự công việc trong mẫu không hợp lệ.');
    end if;

    if exists (
      select 1
      from public.phase_template_stages stage
      left join public.phase_template_tasks task on task.stage_id = stage.id
      where stage.version_id = v_template_version_id
        and (
          (stage.start_offset_days is not null and v_start_date + stage.start_offset_days > v_deadline)
          or (stage.start_offset_days is not null and stage.duration_days is not null
            and v_start_date + stage.start_offset_days + stage.duration_days > v_deadline)
          or (stage.start_offset_days is not null and task.start_offset_days is not null
            and v_start_date + stage.start_offset_days + task.start_offset_days > v_deadline)
        )
    ) then
      return jsonb_build_object('success', false, 'code', 'template_deadline_overflow', 'message', 'Lịch trong mẫu vượt quá hạn hoàn thành dự án.');
    end if;
  else
    for v_task in select * from jsonb_array_elements(coalesce(p_payload->'tasks', '[]'::jsonb)) loop
      v_task_status := upper(coalesce(nullif(v_task->>'status', ''), 'BACKLOG'));
      if v_task_status not in ('BACKLOG','READY','IN_PROGRESS','PENDING_REVIEW','REVISION_REQUIRED','APPROVED','BLOCKED','ON_HOLD','COMPLETED','CANCELLED') then
        return jsonb_build_object('success', false, 'code', 'invalid_task_status', 'message', 'Trạng thái công việc không hợp lệ.');
      end if;
      for v_subtask in select * from jsonb_array_elements(coalesce(v_task->'subtasks', '[]'::jsonb)) loop
        v_task_status := upper(coalesce(nullif(v_subtask->>'status', ''), 'BACKLOG'));
        if v_task_status not in ('BACKLOG','READY','IN_PROGRESS','PENDING_REVIEW','REVISION_REQUIRED','APPROVED','BLOCKED','ON_HOLD','COMPLETED','CANCELLED') then
          return jsonb_build_object('success', false, 'code', 'invalid_task_status', 'message', 'Trạng thái công việc không hợp lệ.');
        end if;
      end loop;
    end loop;
  end if;

  insert into public.projects(project_name, project_code, status, drive_url, start_date, project_deadline)
  values (v_project_name, v_project_code, v_status, '', v_start_date, v_deadline)
  returning id into v_project_id;

  insert into public.project_members(project_id, employee_id, role_code, status, granted_by_employee_id)
  values (v_project_id, v_employee_id, 'PROJECT_OWNER', 'ACTIVE', v_employee_id)
  on conflict do nothing;

  insert into public.project_members(project_id, employee_id, role_code, status, granted_by_employee_id)
  values (v_project_id, v_manager_employee_id, 'PROJECT_MANAGER', 'ACTIVE', v_employee_id)
  on conflict do nothing;

  for v_assignee in
    select jsonb_array_elements_text(coalesce(p_payload->'memberEmployeeIds', '[]'::jsonb))::bigint
  loop
    insert into public.project_members(project_id, employee_id, role_code, status, granted_by_employee_id)
    values (v_project_id, v_assignee, 'CONTRIBUTOR', 'ACTIVE', v_employee_id)
    on conflict do nothing;
  end loop;

  if v_template_version_id is not null then
    for v_template_stage in
      select stage.*
      from public.phase_template_stages stage
      where stage.version_id = v_template_version_id
      order by stage.order_index
    loop
      v_phase_start := case when v_template_stage.start_offset_days is null then null else v_start_date + v_template_stage.start_offset_days end;
      v_phase_end := case when v_phase_start is null or v_template_stage.duration_days is null then null else v_phase_start + v_template_stage.duration_days end;

      insert into public.phases(
        project_id, name, order_index, stage_type, planned_start_date,
        planned_end_date, progress, next_action, required_review
      )
      values (
        v_project_id, v_template_stage.name, v_template_stage.order_index - 1,
        'PHASE_TEMPLATE', to_char(v_phase_start, 'YYYY-MM-DD'),
        to_char(v_phase_end, 'YYYY-MM-DD'), 0,
        (select task.name from public.phase_template_tasks task where task.stage_id = v_template_stage.id order by task.order_index limit 1),
        v_template_stage.requires_review
      )
      returning id into v_phase_id;

      for v_template_task in
        select task.*
        from public.phase_template_tasks task
        where task.stage_id = v_template_stage.id
        order by task.order_index
      loop
        v_assignee := null;
        v_assignee_name := null;
        if v_template_task.assignee_role_code is not null then
          if v_template_task.assignee_role_code = 'PROJECT_MANAGER' then
            select membership.employee_id, employee.full_name
              into v_assignee, v_assignee_name
            from public.project_members membership
            join public.employees employee on employee.id = membership.employee_id
            where membership.project_id = v_project_id
              and membership.employee_id = v_manager_employee_id
              and membership.status = 'ACTIVE'
              and coalesce(employee.is_active, true) = true
              and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
            limit 1;
          else
            select membership.employee_id, employee.full_name
              into v_assignee, v_assignee_name
            from public.project_members membership
            join public.employees employee on employee.id = membership.employee_id
            where membership.project_id = v_project_id
              and membership.role_code = v_template_task.assignee_role_code
              and membership.status = 'ACTIVE'
              and coalesce(employee.is_active, true) = true
              and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
            order by membership.employee_id
            limit 1;
          end if;
        end if;
        if v_template_task.assignee_role_code is not null and v_assignee is null then
          v_unassigned_task_count := v_unassigned_task_count + 1;
        end if;

        v_task_deadline := case
          when v_template_stage.start_offset_days is null or v_template_task.start_offset_days is null then null
          else v_start_date + v_template_stage.start_offset_days + v_template_task.start_offset_days
        end;

        insert into public.tasks(
          project_id, phase_id, project_name, assigned_to, current_phase,
          title, description, assignee_employee_id, deadline, status,
          created_by_employee_id, updated_by_employee_id,
          assigned_by_employee_id, assigned_at, is_required, requires_review
        )
        values (
          v_project_id, v_phase_id, v_project_name, coalesce(v_assignee_name, ''), 'IN_PROG',
          v_template_task.name, v_template_task.description, v_assignee,
          v_task_deadline::timestamptz, 'BACKLOG', v_employee_id, v_employee_id,
          case when v_assignee is null then null else v_employee_id end,
          case when v_assignee is null then null else now() end,
          v_template_task.is_required, v_template_task.requires_review
        )
        returning id into v_task_id;

        v_template_task_count := v_template_task_count + 1;
        insert into public.project_activity(project_id, task_id, actor_employee_id, activity_type, payload)
        values (v_project_id, v_task_id, v_employee_id, 'TASK_CREATED', jsonb_build_object(
          'status', 'BACKLOG', 'templateVersionId', v_template_version_id,
          'assigneeRoleCode', v_template_task.assignee_role_code,
          'assigneeResolved', v_assignee is not null
        ));
        if v_assignee is not null then
          insert into public.task_notifications(project_id, task_id, recipient_employee_id, notification_type, payload)
          values (v_project_id, v_task_id, v_assignee, 'TASK_ASSIGNED', jsonb_build_object('projectId', v_project_id));
        end if;
      end loop;
    end loop;

    insert into public.phase_template_applications(
      project_id, template_id, version_id, applied_by_employee_id, clone_summary
    ) values (
      v_project_id, v_template_id, v_template_version_id, v_employee_id,
      jsonb_build_object(
        'startDate', v_start_date, 'projectDeadline', v_deadline,
        'phasesCreated', v_template_stage_count,
        'tasksCreated', v_template_task_count,
        'unassignedTasks', v_unassigned_task_count
      )
    );

    insert into public.phase_template_audit(
      template_id, version_id, actor_employee_id, action, after_data
    ) values (
      v_template_id, v_template_version_id, v_employee_id, 'APPLIED',
      jsonb_build_object('projectId', v_project_id, 'startDate', v_start_date, 'projectDeadline', v_deadline)
    );
  else
    for v_phase in select * from jsonb_array_elements(coalesce(p_payload->'phases', '[]'::jsonb)) loop
      insert into public.phases(project_id, name, order_index)
      values (v_project_id, nullif(btrim(v_phase->>'name'), ''), coalesce((v_phase->>'orderIndex')::int, 0))
      returning id into v_phase_id;
      if v_phase ? 'clientId' then
        v_phase_map := v_phase_map || jsonb_build_object(v_phase->>'clientId', v_phase_id);
      end if;
    end loop;

    for v_task in select * from jsonb_array_elements(coalesce(p_payload->'tasks', '[]'::jsonb)) loop
      v_task_key := coalesce(v_task->>'clientId', gen_random_uuid()::text);
      v_phase_id := null;
      if v_task ? 'phaseClientId' then v_phase_id := (v_phase_map->>(v_task->>'phaseClientId'))::bigint; end if;
      v_assignee := nullif(v_task->>'assigneeEmployeeId', '')::bigint;
      if v_assignee is not null and not exists (
        select 1 from public.project_members membership
        join public.employees employee on employee.id = membership.employee_id
        where membership.project_id = v_project_id and membership.employee_id = v_assignee
          and membership.status = 'ACTIVE' and coalesce(employee.is_active, true) = true
          and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
      ) then raise exception 'invalid assignee' using errcode = 'P0001'; end if;
      v_task_status := upper(coalesce(nullif(v_task->>'status', ''), 'BACKLOG'));
      insert into public.tasks(project_id, phase_id, project_name, assigned_to, current_phase, title, description, assignee_employee_id, deadline, status, created_by_employee_id, updated_by_employee_id, assigned_by_employee_id, assigned_at)
      values (v_project_id, v_phase_id, v_project_name, '', 'IN_PROG', nullif(btrim(v_task->>'title'), ''), nullif(v_task->>'description', ''), v_assignee, nullif(v_task->>'deadline', '')::timestamptz, v_task_status, v_employee_id, v_employee_id, case when v_assignee is null then null else v_employee_id end, case when v_assignee is null then null else now() end)
      returning id into v_task_id;
      v_task_map := v_task_map || jsonb_build_object(v_task_key, v_task_id);
      v_note := nullif(btrim(coalesce(v_task->>'note', v_task->>'comment')), '');
      if v_note is not null then insert into public.task_comments(task_id, project_id, employee_id, body) values (v_task_id, v_project_id, v_employee_id, v_note); end if;
      insert into public.project_activity(project_id, task_id, actor_employee_id, activity_type, payload) values (v_project_id, v_task_id, v_employee_id, 'TASK_CREATED', jsonb_build_object('status', v_task_status));
      if v_assignee is not null then insert into public.task_notifications(project_id, task_id, recipient_employee_id, notification_type, payload) values (v_project_id, v_task_id, v_assignee, 'TASK_ASSIGNED', jsonb_build_object('projectId', v_project_id)); end if;
      for v_subtask in select * from jsonb_array_elements(coalesce(v_task->'subtasks', '[]'::jsonb)) loop
        v_assignee := nullif(v_subtask->>'assigneeEmployeeId', '')::bigint;
        if v_assignee is not null and not exists (
          select 1 from public.project_members membership
          join public.employees employee on employee.id = membership.employee_id
          where membership.project_id = v_project_id and membership.employee_id = v_assignee
            and membership.status = 'ACTIVE' and coalesce(employee.is_active, true) = true
            and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
        ) then raise exception 'invalid subtask assignee' using errcode = 'P0001'; end if;
        v_task_status := upper(coalesce(nullif(v_subtask->>'status', ''), 'BACKLOG'));
        insert into public.tasks(project_id, phase_id, parent_task_id, project_name, assigned_to, current_phase, title, description, assignee_employee_id, deadline, status, created_by_employee_id, updated_by_employee_id, assigned_by_employee_id, assigned_at)
        values (v_project_id, v_phase_id, v_task_id, v_project_name, '', 'IN_PROG', nullif(btrim(v_subtask->>'title'), ''), nullif(v_subtask->>'description', ''), v_assignee, nullif(v_subtask->>'deadline', '')::timestamptz, v_task_status, v_employee_id, v_employee_id, case when v_assignee is null then null else v_employee_id end, case when v_assignee is null then null else now() end)
        returning id into v_subtask_id;
      end loop;
    end loop;
  end if;

  insert into public.project_activity(project_id, actor_employee_id, activity_type, payload)
  values (v_project_id, v_employee_id, 'PROJECT_CREATED', jsonb_build_object(
    'projectCode', v_project_code, 'templateVersionId', v_template_version_id
  ));

  return jsonb_build_object(
    'success', true,
    'projectId', v_project_id,
    'projectCode', v_project_code,
    'deadlinePersisted', v_deadline is not null,
    'managerMembershipCreated', exists (
      select 1 from public.project_members membership
      where membership.project_id = v_project_id
        and membership.employee_id = v_manager_employee_id
        and membership.status = 'ACTIVE'
    ),
    'workflowCreated', v_template_version_id is not null
      or jsonb_array_length(coalesce(p_payload->'phases', '[]'::jsonb)) > 0,
    'phasesCreated', case when v_template_version_id is null then jsonb_array_length(coalesce(p_payload->'phases', '[]'::jsonb)) else v_template_stage_count end,
    'tasksCreated', case when v_template_version_id is null then jsonb_array_length(coalesce(p_payload->'tasks', '[]'::jsonb)) else v_template_task_count end,
    'unassignedTasks', v_unassigned_task_count
  );
exception
  when unique_violation then
    return jsonb_build_object('success', false, 'code', 'duplicate_project_code', 'message', 'Mã dự án đã tồn tại.');
  when invalid_text_representation or datetime_field_overflow then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Dữ liệu ngày hoặc mã nhân sự không hợp lệ.');
  when others then
    return jsonb_build_object('success', false, 'code', 'project_create_failed', 'message', 'Không thể tạo dự án đầy đủ.');
end;
$$;

revoke all on function public.create_project_atomic(jsonb) from public, anon;
grant execute on function public.create_project_atomic(jsonb) to authenticated, service_role;
comment on function public.create_project_atomic(jsonb) is
  'Atomic project creation with optional current Phase Template clone; actor is auth.uid()-derived.';

create or replace function public.phase_template_validate_draft(p_version_id bigint)
returns void
language plpgsql
set search_path = ''
as $$
declare
  v_stage_count integer;
  v_min_order integer;
  v_max_order integer;
begin
  if not exists (
    select 1 from public.phase_template_versions version
    where version.id = p_version_id and version.status = 'DRAFT'
  ) then
    raise exception 'phase_template_draft_required' using errcode = 'P0001';
  end if;

  select count(*), min(stage.order_index), max(stage.order_index)
    into v_stage_count, v_min_order, v_max_order
  from public.phase_template_stages stage
  where stage.version_id = p_version_id;

  if v_stage_count = 0 or v_min_order <> 1 or v_max_order <> v_stage_count then
    raise exception 'phase_template_stage_order_invalid' using errcode = 'P0001';
  end if;

  if exists (
    select 1
    from public.phase_template_tasks task
    join public.phase_template_stages stage on stage.id = task.stage_id
    where stage.version_id = p_version_id
    group by task.stage_id
    having min(task.order_index) <> 1 or max(task.order_index) <> count(*)
  ) then
    raise exception 'phase_template_task_order_invalid' using errcode = 'P0001';
  end if;
end;
$$;

create or replace function public.manage_phase_template_atomic(p_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, auth, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_employee_id bigint;
  v_action text := upper(nullif(btrim(p_payload->>'action'), ''));
  v_reason text := nullif(btrim(p_payload->>'reason'), '');
  v_template_id bigint := nullif(p_payload->>'templateId', '')::bigint;
  v_version_id bigint := nullif(p_payload->>'versionId', '')::bigint;
  v_source_version_id bigint := nullif(p_payload->>'sourceVersionId', '')::bigint;
  v_current_version_id bigint;
  v_new_version_number integer;
  v_stage jsonb;
  v_task jsonb;
  v_stage_id bigint;
  v_stage_order integer;
  v_task_order integer;
  v_before jsonb;
begin
  if v_actor is null then
    return jsonb_build_object('success', false, 'code', 'session_not_verified', 'message', 'Phiên đăng nhập không hợp lệ.');
  end if;
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Dữ liệu mẫu không hợp lệ.');
  end if;

  select employee.id into v_employee_id
  from public.employees employee
  where employee.auth_user_id = v_actor
    and coalesce(employee.is_active, true) = true
    and coalesce(employee.status, 'ACTIVE') = 'ACTIVE'
  limit 1;

  if v_employee_id is null then
    return jsonb_build_object('success', false, 'code', 'actor_not_allowed', 'message', 'Không thể xác định nhân sự thao tác.');
  end if;
  if not (public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('PHASE_TEMPLATE_MANAGE')) then
    return jsonb_build_object('success', false, 'code', 'permission_forbidden', 'message', 'Bạn không có quyền quản lý mẫu giai đoạn.');
  end if;
  if p_payload ? 'actorEmployeeId'
    or p_payload ? 'actor_employee_id'
    or p_payload ? 'createdByEmployeeId'
    or p_payload ? 'updatedByEmployeeId'
    or p_payload ? 'publishedByEmployeeId' then
    return jsonb_build_object('success', false, 'code', 'client_actor_rejected', 'message', 'Dữ liệu người thao tác không hợp lệ.');
  end if;
  if v_action not in ('CREATE_DRAFT', 'UPDATE_DRAFT', 'CLONE_VERSION', 'PUBLISH', 'ARCHIVE', 'RESTORE', 'DELETE_DRAFT') then
    return jsonb_build_object('success', false, 'code', 'invalid_action', 'message', 'Thao tác mẫu không hợp lệ.');
  end if;
  if v_action in ('PUBLISH', 'ARCHIVE', 'RESTORE', 'DELETE_DRAFT') and v_reason is null then
    return jsonb_build_object('success', false, 'code', 'reason_required', 'message', 'Vui lòng nhập lý do thao tác.');
  end if;

  if v_action = 'CREATE_DRAFT' then
    if nullif(btrim(p_payload->>'name'), '') is null then
      return jsonb_build_object('success', false, 'code', 'name_required', 'message', 'Vui lòng nhập tên mẫu.');
    end if;
    insert into public.phase_templates(
      name, description, project_type, status,
      created_by_employee_id, updated_by_employee_id
    ) values (
      btrim(p_payload->>'name'), nullif(btrim(p_payload->>'description'), ''),
      'GENERAL', 'ACTIVE', v_employee_id, v_employee_id
    ) returning id into v_template_id;

    insert into public.phase_template_versions(
      template_id, version_number, status,
      created_by_employee_id, updated_by_employee_id
    ) values (
      v_template_id, 1, 'DRAFT', v_employee_id, v_employee_id
    ) returning id into v_version_id;

    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, after_data)
    values (v_template_id, v_version_id, v_employee_id, 'DRAFT_CREATED', jsonb_build_object('name', btrim(p_payload->>'name'), 'versionNumber', 1));

  elsif v_action = 'UPDATE_DRAFT' then
    select version.template_id into v_template_id
    from public.phase_template_versions version
    where version.id = v_version_id and version.status = 'DRAFT'
    for update;
    if v_template_id is null then
      return jsonb_build_object('success', false, 'code', 'draft_not_found', 'message', 'Không tìm thấy bản nháp có thể sửa.');
    end if;
    if jsonb_typeof(coalesce(p_payload->'stages', '[]'::jsonb)) <> 'array' then
      return jsonb_build_object('success', false, 'code', 'stages_invalid', 'message', 'Danh sách giai đoạn không hợp lệ.');
    end if;

    select jsonb_build_object('name', template.name, 'description', template.description)
      into v_before
    from public.phase_templates template where template.id = v_template_id for update;

    update public.phase_templates
    set name = coalesce(nullif(btrim(p_payload->>'name'), ''), name),
        description = case when p_payload ? 'description' then nullif(btrim(p_payload->>'description'), '') else description end,
        updated_by_employee_id = v_employee_id,
        updated_at = now()
    where id = v_template_id;

    delete from public.phase_template_tasks task
    using public.phase_template_stages stage
    where task.stage_id = stage.id and stage.version_id = v_version_id;
    delete from public.phase_template_stages where version_id = v_version_id;

    v_stage_order := 0;
    for v_stage in select * from jsonb_array_elements(coalesce(p_payload->'stages', '[]'::jsonb)) loop
      v_stage_order := v_stage_order + 1;
      if coalesce((v_stage->>'orderIndex')::integer, v_stage_order) <> v_stage_order then
        raise exception 'phase_template_stage_order_invalid' using errcode = 'P0001';
      end if;
      if nullif(btrim(v_stage->>'name'), '') is null then
        raise exception 'phase_template_stage_name_required' using errcode = 'P0001';
      end if;
      if jsonb_typeof(coalesce(v_stage->'tasks', '[]'::jsonb)) <> 'array' then
        raise exception 'phase_template_tasks_invalid' using errcode = 'P0001';
      end if;

      insert into public.phase_template_stages(
        version_id, name, order_index, start_offset_days,
        duration_days, requires_review
      ) values (
        v_version_id, btrim(v_stage->>'name'), v_stage_order,
        nullif(v_stage->>'startOffsetDays', '')::integer,
        nullif(v_stage->>'durationDays', '')::integer,
        coalesce((v_stage->>'requiresReview')::boolean, false)
      ) returning id into v_stage_id;

      v_task_order := 0;
      for v_task in select * from jsonb_array_elements(coalesce(v_stage->'tasks', '[]'::jsonb)) loop
        v_task_order := v_task_order + 1;
        if coalesce((v_task->>'orderIndex')::integer, v_task_order) <> v_task_order then
          raise exception 'phase_template_task_order_invalid' using errcode = 'P0001';
        end if;
        if nullif(btrim(v_task->>'name'), '') is null then
          raise exception 'phase_template_task_name_required' using errcode = 'P0001';
        end if;
        insert into public.phase_template_tasks(
          stage_id, name, description, order_index, start_offset_days,
          is_required, requires_review, assignee_role_code
        ) values (
          v_stage_id, btrim(v_task->>'name'), nullif(btrim(v_task->>'description'), ''),
          v_task_order, nullif(v_task->>'startOffsetDays', '')::integer,
          coalesce((v_task->>'isRequired')::boolean, true),
          coalesce((v_task->>'requiresReview')::boolean, false),
          nullif(upper(btrim(v_task->>'assigneeRoleCode')), '')
        );
      end loop;
    end loop;

    perform public.phase_template_validate_draft(v_version_id);
    update public.phase_template_versions
    set updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_version_id;
    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, before_data, after_data)
    values (v_template_id, v_version_id, v_employee_id, 'DRAFT_UPDATED', v_before, jsonb_build_object('stageCount', v_stage_order));

  elsif v_action = 'CLONE_VERSION' then
    select version.template_id into v_template_id
    from public.phase_template_versions version
    where version.id = v_source_version_id
    for update;
    if v_template_id is null then
      return jsonb_build_object('success', false, 'code', 'source_version_not_found', 'message', 'Không tìm thấy phiên bản nguồn.');
    end if;
    if exists (select 1 from public.phase_template_versions version where version.template_id = v_template_id and version.status = 'DRAFT') then
      return jsonb_build_object('success', false, 'code', 'draft_already_exists', 'message', 'Mẫu đang có một bản nháp.');
    end if;
    select max(version.version_number) + 1 into v_new_version_number
    from public.phase_template_versions version where version.template_id = v_template_id;

    insert into public.phase_template_versions(
      template_id, version_number, status, source_version_id,
      created_by_employee_id, updated_by_employee_id
    ) values (
      v_template_id, v_new_version_number, 'DRAFT', v_source_version_id,
      v_employee_id, v_employee_id
    ) returning id into v_version_id;

    for v_stage in
      select to_jsonb(stage) from public.phase_template_stages stage
      where stage.version_id = v_source_version_id order by stage.order_index
    loop
      insert into public.phase_template_stages(version_id, name, order_index, start_offset_days, duration_days, requires_review)
      values (v_version_id, v_stage->>'name', (v_stage->>'order_index')::integer,
        nullif(v_stage->>'start_offset_days', '')::integer,
        nullif(v_stage->>'duration_days', '')::integer,
        (v_stage->>'requires_review')::boolean)
      returning id into v_stage_id;

      insert into public.phase_template_tasks(stage_id, name, description, order_index, start_offset_days, is_required, requires_review, assignee_role_code)
      select v_stage_id, task.name, task.description, task.order_index, task.start_offset_days,
        task.is_required, task.requires_review, task.assignee_role_code
      from public.phase_template_tasks task
      where task.stage_id = (v_stage->>'id')::bigint
      order by task.order_index;
    end loop;

    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, after_data)
    values (v_template_id, v_version_id, v_employee_id, 'VERSION_CLONED', jsonb_build_object('sourceVersionId', v_source_version_id, 'versionNumber', v_new_version_number));

  elsif v_action = 'PUBLISH' then
    select version.template_id into v_template_id
    from public.phase_template_versions version
    where version.id = v_version_id and version.status = 'DRAFT'
    for update;
    if v_template_id is null then
      return jsonb_build_object('success', false, 'code', 'draft_not_found', 'message', 'Không tìm thấy bản nháp có thể xuất bản.');
    end if;
    perform public.phase_template_validate_draft(v_version_id);
    select template.current_version_id into v_current_version_id
    from public.phase_templates template where template.id = v_template_id for update;
    update public.phase_templates set current_version_id = null where id = v_template_id;
    if v_current_version_id is not null and v_current_version_id <> v_version_id then
      update public.phase_template_versions
      set status = 'ARCHIVED', archived_at = now(), updated_by_employee_id = v_employee_id, updated_at = now()
      where id = v_current_version_id and status = 'PUBLISHED';
    end if;
    update public.phase_template_versions
    set status = 'PUBLISHED', published_at = now(), archived_at = null,
        updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_version_id;
    update public.phase_templates
    set status = 'ACTIVE', current_version_id = v_version_id,
        updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_template_id;
    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, reason, after_data)
    values (v_template_id, v_version_id, v_employee_id, 'PUBLISHED', v_reason, jsonb_build_object('previousVersionId', v_current_version_id));

  elsif v_action = 'ARCHIVE' then
    select template.id, template.current_version_id into v_template_id, v_version_id
    from public.phase_templates template
    where template.id = v_template_id and template.status = 'ACTIVE'
    for update;
    if v_template_id is null or v_version_id is null then
      return jsonb_build_object('success', false, 'code', 'published_template_not_found', 'message', 'Không tìm thấy mẫu đang hoạt động.');
    end if;
    update public.phase_templates
    set current_version_id = null, status = 'ARCHIVED', updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_template_id;
    update public.phase_template_versions
    set status = 'ARCHIVED', archived_at = now(), updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_version_id and status = 'PUBLISHED';
    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, reason)
    values (v_template_id, v_version_id, v_employee_id, 'ARCHIVED', v_reason);

  elsif v_action = 'RESTORE' then
    select version.template_id into v_template_id
    from public.phase_template_versions version
    join public.phase_templates template on template.id = version.template_id
    where version.id = v_version_id and version.status = 'ARCHIVED' and template.status = 'ARCHIVED'
    for update of version, template;
    if v_template_id is null then
      return jsonb_build_object('success', false, 'code', 'archived_version_not_found', 'message', 'Không tìm thấy phiên bản lưu trữ.');
    end if;
    if exists (select 1 from public.phase_template_versions version where version.template_id = v_template_id and version.status = 'PUBLISHED') then
      return jsonb_build_object('success', false, 'code', 'published_version_exists', 'message', 'Mẫu đã có một phiên bản đang xuất bản.');
    end if;
    update public.phase_template_versions
    set status = 'PUBLISHED', archived_at = null, updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_version_id;
    update public.phase_templates
    set status = 'ACTIVE', current_version_id = v_version_id, updated_by_employee_id = v_employee_id, updated_at = now()
    where id = v_template_id;
    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, reason)
    values (v_template_id, v_version_id, v_employee_id, 'RESTORED', v_reason);

  elsif v_action = 'DELETE_DRAFT' then
    select version.template_id, jsonb_build_object('versionNumber', version.version_number, 'sourceVersionId', version.source_version_id)
      into v_template_id, v_before
    from public.phase_template_versions version
    where version.id = v_version_id and version.status = 'DRAFT'
    for update;
    if v_template_id is null then
      return jsonb_build_object('success', false, 'code', 'draft_not_found', 'message', 'Không tìm thấy bản nháp có thể xóa.');
    end if;
    if exists (select 1 from public.phase_template_applications application where application.version_id = v_version_id)
      or exists (select 1 from public.phase_template_versions version where version.source_version_id = v_version_id) then
      return jsonb_build_object('success', false, 'code', 'draft_in_use', 'message', 'Bản nháp đang được tham chiếu và không thể xóa.');
    end if;
    delete from public.phase_template_tasks task
    using public.phase_template_stages stage
    where task.stage_id = stage.id and stage.version_id = v_version_id;
    delete from public.phase_template_stages where version_id = v_version_id;
    delete from public.phase_template_versions where id = v_version_id;
    insert into public.phase_template_audit(template_id, version_id, actor_employee_id, action, reason, before_data)
    values (v_template_id, null, v_employee_id, 'DRAFT_DELETED', v_reason, v_before);
    v_version_id := null;
  end if;

  return jsonb_build_object('success', true, 'action', v_action, 'templateId', v_template_id, 'versionId', v_version_id);
exception
  when unique_violation then
    return jsonb_build_object('success', false, 'code', 'template_conflict', 'message', 'Tên mẫu, phiên bản hoặc bản nháp đã tồn tại.');
  when check_violation or foreign_key_violation or invalid_text_representation or numeric_value_out_of_range then
    return jsonb_build_object('success', false, 'code', 'payload_validation_failed', 'message', 'Dữ liệu mẫu không hợp lệ.');
  when others then
    return jsonb_build_object('success', false, 'code', 'phase_template_mutation_failed', 'message', 'Không thể cập nhật mẫu giai đoạn.');
end;
$$;

revoke all on function public.phase_template_validate_draft(bigint) from public, anon, authenticated;
revoke all on function public.manage_phase_template_atomic(jsonb) from public, anon;
grant execute on function public.manage_phase_template_atomic(jsonb) to authenticated, service_role;

comment on function public.manage_phase_template_atomic(jsonb) is
  'Authorized atomic Phase Template draft/version lifecycle management.';

commit;

