-- Ledger/Reimbursement delivery through protected main only. Do not execute directly.
begin;

alter table public.financial_ledger
  add column if not exists beneficiary_employee_id bigint references public.employees(id),
  add column if not exists beneficiary_external_name text,
  add column if not exists payer_employee_id bigint references public.employees(id),
  add column if not exists creator_employee_id bigint references public.employees(id),
  add column if not exists reimbursement_requester_employee_id bigint references public.employees(id),
  add column if not exists reimbursement_recipient_employee_id bigint references public.employees(id),
  add column if not exists approver_employee_id bigint references public.employees(id),
  add column if not exists payment_confirmer_employee_id bigint references public.employees(id),
  add column if not exists payment_status text not null default 'UNPAID',
  add column if not exists approval_status text not null default 'NOT_REQUIRED',
  add column if not exists reimbursement_status text,
  add column if not exists payment_method text,
  add column if not exists paid_at timestamptz,
  add column if not exists transfer_reference text,
  add column if not exists payment_note text,
  add column if not exists rejection_reason text,
  add column if not exists idempotency_key text;

create unique index if not exists financial_ledger_idempotency_key_unique_idx
  on public.financial_ledger (idempotency_key)
  where idempotency_key is not null;

create table if not exists public.finance_expense_attachments (
  id bigserial primary key,
  financial_ledger_id bigint not null references public.financial_ledger(id) on delete cascade,
  uploaded_by_employee_id bigint not null references public.employees(id),
  attachment_type text not null,
  storage_bucket text not null,
  storage_path text not null,
  original_filename text not null,
  mime_type text not null,
  size_bytes bigint not null,
  verification_state text not null default 'UNVERIFIED',
  created_at timestamptz not null default now(),
  constraint finance_expense_attachments_mime_type_check check (mime_type in ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')),
  constraint finance_expense_attachments_size_check check (size_bytes > 0 and size_bytes <= 10485760),
  constraint finance_expense_attachments_path_check check (storage_path !~ '[[:cntrl:]]')
);

alter table public.finance_expense_attachments enable row level security;

-- RLS plan: SELECT only for FINANCE_VIEW or row-owner employee self-service reimbursement visibility;
-- INSERT through reviewed server boundary only; no public URLs for protected finance documents.


-- Approved Ledger/Reimbursement contract. Legacy columns and rows are intentionally untouched.

insert into public.permissions(code, description) values
 ('FINANCE_APPROVE','Approve or reject reimbursement requests'),
 ('FINANCE_PAY','Confirm reimbursement payment')
on conflict (code) do nothing;

alter table public.financial_ledger
  add column if not exists transaction_date date,
  add column if not exists description text,
  add column if not exists project_id bigint references public.projects(id) on delete restrict,
  add column if not exists source_type text,
  add column if not exists source_reference text,
  add column if not exists cancelled_at timestamptz,
  add column if not exists updated_at timestamptz;

alter table public.financial_ledger
  add constraint financial_ledger_reimbursement_status_check check (reimbursement_status is null or reimbursement_status in ('DRAFT','SUBMITTED','APPROVED','REJECTED','PAID','CANCELLED')),
  add constraint financial_ledger_payment_status_check check (payment_status in ('UNPAID','PAID')),
  add constraint financial_ledger_beneficiary_kind_check check (beneficiary_employee_id is null or beneficiary_external_name is null),
  add constraint financial_ledger_source_identity_unique unique (source_type, source_reference);

alter table public.finance_expense_attachments drop constraint if exists finance_expense_attachments_financial_ledger_id_fkey;
alter table public.finance_expense_attachments add constraint finance_expense_attachments_financial_ledger_id_fkey foreign key(financial_ledger_id) references public.financial_ledger(id) on delete restrict;

create table public.finance_ledger_history (
 id bigint generated by default as identity primary key,
 financial_ledger_id bigint not null references public.financial_ledger(id) on delete restrict,
 event_type text not null check(event_type in ('CREATED','SUBMITTED','APPROVED','REJECTED','PAID','CANCELLED')),
 from_status text,
 to_status text not null,
 actor_employee_id bigint not null references public.employees(id) on delete restrict,
 reason text,
 idempotency_key text not null unique,
 occurred_at timestamptz not null default clock_timestamp(),
 details jsonb not null default '{}'::jsonb
);

create or replace function public.block_finance_history_change() returns trigger language plpgsql set search_path=public,pg_temp as $$
begin raise exception 'finance history is immutable'; end $$;
create trigger finance_ledger_history_immutable before update or delete on public.finance_ledger_history for each row execute function public.block_finance_history_change();

create or replace function public.block_financial_ledger_delete() returns trigger language plpgsql set search_path=public,pg_temp as $$
begin raise exception 'financial ledger records cannot be deleted'; end $$;
create trigger financial_ledger_no_delete before delete on public.financial_ledger for each row execute function public.block_financial_ledger_delete();

create or replace function public.submit_my_reimbursement(p_amount numeric,p_transaction_date date,p_category text,p_description text,p_project_id bigint,p_beneficiary_employee_id bigint,p_beneficiary_external_name text,p_payer_employee_id bigint,p_idempotency_key text,p_receipt_url text default null)
returns bigint language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare actor bigint:=public.current_employee_id(); result bigint; stamp timestamptz:=clock_timestamp(); beneficiary bigint;
begin
 if actor is null or not public.has_workspace_access('STAFF_WORKSPACE') then raise exception 'reimbursement forbidden' using errcode='42501'; end if;
 if p_amount <= 0 or p_transaction_date is null or length(btrim(p_category))<1 or length(btrim(p_description))<1 then raise exception 'invalid reimbursement'; end if;
 beneficiary:=coalesce(p_beneficiary_employee_id,actor);
 if beneficiary<>actor then raise exception 'employee may only submit own-beneficiary reimbursement' using errcode='42501'; end if;
 if p_beneficiary_external_name is not null then raise exception 'employee reimbursement external beneficiary forbidden' using errcode='42501'; end if;
 insert into public.financial_ledger(type,category,amount,bill_url,requested_by,is_paid,month_period,transaction_date,description,project_id,beneficiary_employee_id,payer_employee_id,creator_employee_id,reimbursement_requester_employee_id,reimbursement_recipient_employee_id,payment_status,approval_status,reimbursement_status,idempotency_key,created_at,updated_at)
 select 'HOAN_UNG',btrim(p_category),p_amount,nullif(btrim(p_receipt_url),''),e.full_name,false,to_char(p_transaction_date,'MM/YYYY'),p_transaction_date,btrim(p_description),p_project_id,beneficiary,p_payer_employee_id,actor,actor,beneficiary,'UNPAID','PENDING','SUBMITTED',p_idempotency_key,stamp,stamp from public.employees e where e.id=actor returning id into result;
 insert into public.finance_ledger_history(financial_ledger_id,event_type,to_status,actor_employee_id,idempotency_key,occurred_at) values(result,'SUBMITTED','SUBMITTED',actor,p_idempotency_key,stamp);
 return result;
end $$;

create or replace function public.transition_reimbursement(p_ledger_id bigint,p_status text,p_reason text,p_idempotency_key text)
returns text language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare actor bigint:=public.current_employee_id(); current_status text; requester bigint; stamp timestamptz:=clock_timestamp(); permission text; event text;
begin
 if p_status not in ('APPROVED','REJECTED','PAID') then raise exception 'invalid reimbursement transition'; end if;
 permission:=case when p_status='PAID' then 'FINANCE_PAY' else 'FINANCE_APPROVE' end;
 if actor is null or not public.has_workspace_access('ADMIN_WORKSPACE') or not public.has_permission(permission) then raise exception 'reimbursement transition forbidden' using errcode='42501'; end if;
 select reimbursement_status,reimbursement_requester_employee_id into current_status,requester from public.financial_ledger where id=p_ledger_id for update;
 if requester=actor then raise exception 'self approval/payment forbidden' using errcode='42501'; end if;
 if (p_status in ('APPROVED','REJECTED') and current_status<>'SUBMITTED') or (p_status='PAID' and current_status<>'APPROVED') then raise exception 'invalid reimbursement transition'; end if;
 if p_status='REJECTED' and length(btrim(coalesce(p_reason,'')))<3 then raise exception 'rejection reason required'; end if;
 update public.financial_ledger set reimbursement_status=p_status, approval_status=case when p_status='APPROVED' then 'APPROVED' when p_status='REJECTED' then 'REJECTED' else approval_status end, approver_employee_id=case when p_status in ('APPROVED','REJECTED') then actor else approver_employee_id end, payment_status=case when p_status='PAID' then 'PAID' else payment_status end, is_paid=case when p_status='PAID' then true else is_paid end, payment_confirmer_employee_id=case when p_status='PAID' then actor else payment_confirmer_employee_id end, paid_at=case when p_status='PAID' then stamp else paid_at end, rejection_reason=case when p_status='REJECTED' then btrim(p_reason) else rejection_reason end, updated_at=stamp where id=p_ledger_id;
 event:=p_status;
 insert into public.finance_ledger_history(financial_ledger_id,event_type,from_status,to_status,actor_employee_id,reason,idempotency_key,occurred_at) values(p_ledger_id,event,current_status,p_status,actor,nullif(btrim(p_reason),''),p_idempotency_key,stamp);
 return p_status;
end $$;

create or replace function public.list_my_reimbursements() returns table(id bigint,type text,category text,amount numeric,bill_url text,transaction_date date,description text,project_id bigint,beneficiary_employee_id bigint,beneficiary_name text,month_period text,payer_employee_id bigint,payer_name text,reimbursement_status text,rejection_reason text,created_at timestamptz)
language sql stable security definer set search_path=public,auth,pg_temp as $$
 select fl.id,fl.type,fl.category,fl.amount,fl.bill_url,fl.transaction_date,fl.description,fl.project_id,fl.beneficiary_employee_id,coalesce(b.full_name,fl.beneficiary_external_name,'Chưa xác định'),fl.month_period,fl.payer_employee_id,p.full_name,fl.reimbursement_status,fl.rejection_reason,fl.created_at
 from public.financial_ledger fl left join public.employees b on b.id=fl.beneficiary_employee_id left join public.employees p on p.id=fl.payer_employee_id
 where public.has_workspace_access('STAFF_WORKSPACE') and (fl.reimbursement_requester_employee_id=public.current_employee_id() or fl.beneficiary_employee_id=public.current_employee_id()) order by fl.id desc;
$$;

alter table public.finance_ledger_history enable row level security;
create policy "finance history admin select" on public.finance_ledger_history for select to authenticated using(public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('FINANCE_VIEW'));
create policy "finance history own select" on public.finance_ledger_history for select to authenticated using(exists(select 1 from public.financial_ledger fl where fl.id=financial_ledger_id and (fl.reimbursement_requester_employee_id=public.current_employee_id() or fl.beneficiary_employee_id=public.current_employee_id())));
create policy "finance attachments admin select" on public.finance_expense_attachments for select to authenticated using(public.has_workspace_access('ADMIN_WORKSPACE') and public.has_permission('FINANCE_VIEW'));
create policy "finance attachments own select" on public.finance_expense_attachments for select to authenticated using(exists(select 1 from public.financial_ledger fl where fl.id=financial_ledger_id and (fl.reimbursement_requester_employee_id=public.current_employee_id() or fl.beneficiary_employee_id=public.current_employee_id())));

revoke all on public.finance_ledger_history,public.finance_expense_attachments from anon,authenticated;
grant select on public.finance_ledger_history,public.finance_expense_attachments to authenticated;
revoke all on function public.submit_my_reimbursement(numeric,date,text,text,bigint,bigint,text,bigint,text,text),public.transition_reimbursement(bigint,text,text,text),public.list_my_reimbursements() from public,anon;
grant execute on function public.submit_my_reimbursement(numeric,date,text,text,bigint,bigint,text,bigint,text,text),public.transition_reimbursement(bigint,text,text,text),public.list_my_reimbursements() to authenticated;
commit;
