-- Project Membership Slice 2: atomic add/change-role/revoke with immutable audit.
-- Delivery only: the application runtime gate remains false/unset until operator
-- validation completes. This migration performs no membership backfill.

begin;

do $$
begin
  if to_regclass('public.projects') is null
    or to_regclass('public.employees') is null
    or to_regclass('public.project_members') is null then
    raise exception 'Precondition failed: project membership foundation is incomplete.';
  end if;

  if exists (
    select 1
    from public.project_members
    where status = 'ACTIVE'
    group by project_id, employee_id
    having count(*) > 1
  ) then
    raise exception 'Precondition failed: duplicate ACTIVE project memberships require reviewed reconciliation.';
  end if;
end $$;

drop index if exists public.project_members_one_active_role;
create unique index if not exists project_members_one_active_employee
  on public.project_members(project_id, employee_id)
  where status = 'ACTIVE';

create table if not exists public.project_membership_audit (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on update cascade on delete restrict,
  membership_id bigint not null references public.project_members(id) on update cascade on delete restrict,
  employee_id bigint not null references public.employees(id) on update cascade on delete restrict,
  actor_employee_id bigint not null references public.employees(id) on update cascade on delete restrict,
  operation text not null check (operation in ('ADD', 'CHANGE_ROLE', 'REVOKE')),
  reason text not null check (length(btrim(reason)) between 10 and 500),
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  correlation_id uuid not null unique,
  occurred_at timestamptz not null default clock_timestamp()
);

create index if not exists project_membership_audit_project_occurred_idx
  on public.project_membership_audit(project_id, occurred_at desc);
create index if not exists project_membership_audit_employee_occurred_idx
  on public.project_membership_audit(employee_id, occurred_at desc);
create index if not exists project_membership_audit_actor_occurred_idx
  on public.project_membership_audit(actor_employee_id, occurred_at desc);

create or replace function public.reject_project_membership_audit_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'Project membership audit rows are immutable.';
end;
$$;

drop trigger if exists project_membership_audit_immutable on public.project_membership_audit;
create trigger project_membership_audit_immutable
before update or delete on public.project_membership_audit
for each row execute function public.reject_project_membership_audit_mutation();

alter table public.project_membership_audit enable row level security;
revoke all on public.project_membership_audit from public, anon, authenticated;
revoke all on sequence public.project_membership_audit_id_seq from public, anon, authenticated;

create or replace function public.mutate_project_membership(
  p_operation text,
  p_project_id bigint,
  p_membership_id bigint,
  p_employee_id bigint,
  p_role_code text,
  p_actor_employee_id bigint,
  p_reason text,
  p_correlation_id uuid
)
returns jsonb
language plpgsql
security invoker
set search_path = public, pg_temp
as $$
declare
  v_project_status text;
  v_actor_role text;
  v_authorized boolean := false;
  v_membership public.project_members%rowtype;
  v_after public.project_members%rowtype;
  v_existing_membership_id bigint;
  v_operation text := upper(btrim(coalesce(p_operation, '')));
  v_role_code text := upper(btrim(coalesce(p_role_code, '')));
  v_reason text := btrim(coalesce(p_reason, ''));
begin
  if p_project_id is null or p_project_id <= 0
    or p_actor_employee_id is null or p_actor_employee_id <= 0
    or p_correlation_id is null
    or v_operation not in ('ADD', 'CHANGE_ROLE', 'REVOKE')
    or length(v_reason) not between 10 and 500 then
    raise exception 'project_membership_invalid_input';
  end if;

  select membership_id
  into v_existing_membership_id
  from public.project_membership_audit
  where correlation_id = p_correlation_id;
  if found then
    return jsonb_build_object('success', true, 'membership_id', v_existing_membership_id, 'replayed', true);
  end if;

  select p.status
  into v_project_status
  from public.projects p
  where p.id = p_project_id
  for update;
  if not found then
    raise exception 'project_membership_project_not_found';
  end if;
  if upper(coalesce(v_project_status, '')) = 'CANCELLED' then
    raise exception 'project_membership_project_cancelled';
  end if;

  select upper(coalesce(e.role, ''))
  into v_actor_role
  from public.employees e
  where e.id = p_actor_employee_id
    and coalesce(e.is_active, true) = true
    and upper(coalesce(e.status, 'ACTIVE')) = 'ACTIVE';
  if not found then
    raise exception 'project_membership_permission_forbidden';
  end if;

  v_authorized := v_actor_role in ('ADMIN', 'OWNER')
    or exists (
      select 1
      from public.project_members pm
      where pm.project_id = p_project_id
        and pm.employee_id = p_actor_employee_id
        and pm.status = 'ACTIVE'
        and pm.role_code in ('PROJECT_OWNER', 'PROJECT_MANAGER')
    )
    or (
      exists (
        select 1 from public.employee_workspace_access ewa
        where ewa.employee_id = p_actor_employee_id
          and ewa.workspace = 'ADMIN_WORKSPACE'
          and ewa.status = 'ACTIVE'
          and ewa.revoked_at is null
      )
      and exists (
        select 1 from public.employee_permissions ep
        where ep.employee_id = p_actor_employee_id
          and ep.permission_code = 'PROJECT_MANAGE'
          and ep.effect = 'ALLOW'
          and ep.status = 'ACTIVE'
          and ep.revoked_at is null
      )
      and not exists (
        select 1 from public.employee_permissions ep
        where ep.employee_id = p_actor_employee_id
          and ep.permission_code = 'PROJECT_MANAGE'
          and ep.effect = 'DENY'
          and ep.status = 'ACTIVE'
          and ep.revoked_at is null
      )
    );
  if not v_authorized then
    raise exception 'project_membership_permission_forbidden';
  end if;

  if v_operation = 'ADD' then
    if p_employee_id is null or p_employee_id <= 0
      or v_role_code not in ('PROJECT_OWNER', 'PROJECT_MANAGER', 'CREATIVE_LEAD', 'CONTRIBUTOR') then
      raise exception 'project_membership_invalid_input';
    end if;
    if not exists (
      select 1 from public.employees e
      where e.id = p_employee_id
        and coalesce(e.is_active, true) = true
        and upper(coalesce(e.status, 'ACTIVE')) = 'ACTIVE'
    ) then
      raise exception 'project_membership_employee_inactive';
    end if;
    if exists (
      select 1 from public.project_members pm
      where pm.project_id = p_project_id and pm.employee_id = p_employee_id and pm.status = 'ACTIVE'
    ) then
      raise exception 'project_membership_duplicate_active';
    end if;

    insert into public.project_members(
      project_id, employee_id, role_code, status, granted_by_employee_id
    ) values (
      p_project_id, p_employee_id, v_role_code, 'ACTIVE', p_actor_employee_id
    ) returning * into v_after;

    insert into public.project_membership_audit(
      project_id, membership_id, employee_id, actor_employee_id, operation,
      reason, before_state, after_state, correlation_id
    ) values (
      p_project_id, v_after.id, v_after.employee_id, p_actor_employee_id, v_operation,
      v_reason, '{}'::jsonb, to_jsonb(v_after), p_correlation_id
    );
    return jsonb_build_object('success', true, 'membership_id', v_after.id);
  end if;

  select *
  into v_membership
  from public.project_members pm
  where pm.id = p_membership_id
    and pm.project_id = p_project_id
    and pm.status = 'ACTIVE'
  for update;
  if not found then
    raise exception 'project_membership_not_found';
  end if;

  if v_operation = 'CHANGE_ROLE' then
    if v_role_code not in ('PROJECT_OWNER', 'PROJECT_MANAGER', 'CREATIVE_LEAD', 'CONTRIBUTOR') then
      raise exception 'project_membership_invalid_input';
    end if;
    if v_membership.role_code = v_role_code then
      insert into public.project_membership_audit(
        project_id, membership_id, employee_id, actor_employee_id, operation,
        reason, before_state, after_state, correlation_id
      ) values (
        p_project_id, v_membership.id, v_membership.employee_id, p_actor_employee_id,
        v_operation, v_reason, to_jsonb(v_membership), to_jsonb(v_membership), p_correlation_id
      );
      return jsonb_build_object('success', true, 'membership_id', v_membership.id);
    end if;
    if v_membership.role_code = 'PROJECT_OWNER'
      and v_role_code <> 'PROJECT_OWNER'
      and (select count(*) from public.project_members pm where pm.project_id = p_project_id and pm.role_code = 'PROJECT_OWNER' and pm.status = 'ACTIVE') <= 1 then
      raise exception 'project_membership_last_owner';
    end if;

    update public.project_members
    set status = 'REVOKED', revoked_at = clock_timestamp(),
        revoked_by_employee_id = p_actor_employee_id
    where id = v_membership.id;

    insert into public.project_members(
      project_id, employee_id, role_code, status, granted_by_employee_id
    ) values (
      p_project_id, v_membership.employee_id, v_role_code, 'ACTIVE', p_actor_employee_id
    ) returning * into v_after;

    insert into public.project_membership_audit(
      project_id, membership_id, employee_id, actor_employee_id, operation,
      reason, before_state, after_state, correlation_id
    ) values (
      p_project_id, v_after.id, v_after.employee_id, p_actor_employee_id, v_operation,
      v_reason, to_jsonb(v_membership), to_jsonb(v_after), p_correlation_id
    );
    return jsonb_build_object('success', true, 'membership_id', v_after.id);
  end if;

  if v_membership.role_code = 'PROJECT_OWNER'
    and (select count(*) from public.project_members pm where pm.project_id = p_project_id and pm.role_code = 'PROJECT_OWNER' and pm.status = 'ACTIVE') <= 1 then
    raise exception 'project_membership_last_owner';
  end if;
  if to_regclass('public.tasks') is not null and exists (
    select 1
    from public.tasks t
    where t.project_id = p_project_id
      and nullif(to_jsonb(t)->>'assignee_employee_id', '')::bigint = v_membership.employee_id
      and upper(coalesce(to_jsonb(t)->>'status', '')) not in ('COMPLETED', 'CANCELLED')
  ) then
    raise exception 'project_membership_active_tasks';
  end if;

  update public.project_members
  set status = 'REVOKED', revoked_at = clock_timestamp(),
      revoked_by_employee_id = p_actor_employee_id
  where id = v_membership.id
  returning * into v_after;

  insert into public.project_membership_audit(
    project_id, membership_id, employee_id, actor_employee_id, operation,
    reason, before_state, after_state, correlation_id
  ) values (
    p_project_id, v_after.id, v_after.employee_id, p_actor_employee_id, v_operation,
    v_reason, to_jsonb(v_membership), to_jsonb(v_after), p_correlation_id
  );
  return jsonb_build_object('success', true, 'membership_id', v_after.id);
end;
$$;

revoke insert, update, delete on public.project_members from authenticated;
revoke usage on sequence public.project_members_id_seq from authenticated;

revoke all on function public.mutate_project_membership(text, bigint, bigint, bigint, text, bigint, text, uuid)
  from public, anon, authenticated;
grant execute on function public.mutate_project_membership(text, bigint, bigint, bigint, text, bigint, text, uuid)
  to service_role;

comment on table public.project_membership_audit is
  'Immutable before/after audit for atomic project membership mutations.';
comment on function public.mutate_project_membership(text, bigint, bigint, bigint, text, bigint, text, uuid) is
  'Atomic service-role-only membership mutation. Revalidates actor, project, owner, duplicate, active-task and audit invariants.';

commit;
